// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexlad/konservi/ent/entry"
	"github.com/plexlad/konservi/ent/project"
	"github.com/plexlad/konservi/ent/user"
)

// Entry is the model entity for the Entry schema.
type Entry struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// AuthorID holds the value of the "author_id" field.
	AuthorID uuid.UUID `json:"author_id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// EntryDate holds the value of the "entry_date" field.
	EntryDate time.Time `json:"entry_date,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// EditedLastAt holds the value of the "edited_last_at" field.
	EditedLastAt time.Time `json:"edited_last_at,omitempty"`
	// LinkedPersonIds holds the value of the "linked_person_ids" field.
	LinkedPersonIds []uuid.UUID `json:"linked_person_ids,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntryQuery when eager-loading is set.
	Edges          EntryEdges `json:"edges"`
	family_entries *uuid.UUID
	person_entries *uuid.UUID
	selectValues   sql.SelectValues
}

// EntryEdges holds the relations/edges for other nodes in the graph.
type EntryEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Author holds the value of the author edge.
	Author *User `json:"author,omitempty"`
	// LinkedPeople holds the value of the linked_people edge.
	LinkedPeople []*Person `json:"linked_people,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntryEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// AuthorOrErr returns the Author value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntryEdges) AuthorOrErr() (*User, error) {
	if e.Author != nil {
		return e.Author, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "author"}
}

// LinkedPeopleOrErr returns the LinkedPeople value or an error if the edge
// was not loaded in eager-loading.
func (e EntryEdges) LinkedPeopleOrErr() ([]*Person, error) {
	if e.loadedTypes[2] {
		return e.LinkedPeople, nil
	}
	return nil, &NotLoadedError{edge: "linked_people"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Entry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entry.FieldLinkedPersonIds:
			values[i] = new([]byte)
		case entry.FieldContent:
			values[i] = new(sql.NullString)
		case entry.FieldEntryDate, entry.FieldCreatedAt, entry.FieldEditedLastAt:
			values[i] = new(sql.NullTime)
		case entry.FieldID, entry.FieldProjectID, entry.FieldAuthorID:
			values[i] = new(uuid.UUID)
		case entry.ForeignKeys[0]: // family_entries
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case entry.ForeignKeys[1]: // person_entries
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Entry fields.
func (_m *Entry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entry.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case entry.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case entry.FieldAuthorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field author_id", values[i])
			} else if value != nil {
				_m.AuthorID = *value
			}
		case entry.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case entry.FieldEntryDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field entry_date", values[i])
			} else if value.Valid {
				_m.EntryDate = value.Time
			}
		case entry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case entry.FieldEditedLastAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field edited_last_at", values[i])
			} else if value.Valid {
				_m.EditedLastAt = value.Time
			}
		case entry.FieldLinkedPersonIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field linked_person_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.LinkedPersonIds); err != nil {
					return fmt.Errorf("unmarshal field linked_person_ids: %w", err)
				}
			}
		case entry.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field family_entries", values[i])
			} else if value.Valid {
				_m.family_entries = new(uuid.UUID)
				*_m.family_entries = *value.S.(*uuid.UUID)
			}
		case entry.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field person_entries", values[i])
			} else if value.Valid {
				_m.person_entries = new(uuid.UUID)
				*_m.person_entries = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Entry.
// This includes values selected through modifiers, order, etc.
func (_m *Entry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Entry entity.
func (_m *Entry) QueryProject() *ProjectQuery {
	return NewEntryClient(_m.config).QueryProject(_m)
}

// QueryAuthor queries the "author" edge of the Entry entity.
func (_m *Entry) QueryAuthor() *UserQuery {
	return NewEntryClient(_m.config).QueryAuthor(_m)
}

// QueryLinkedPeople queries the "linked_people" edge of the Entry entity.
func (_m *Entry) QueryLinkedPeople() *PersonQuery {
	return NewEntryClient(_m.config).QueryLinkedPeople(_m)
}

// Update returns a builder for updating this Entry.
// Note that you need to call Entry.Unwrap() before calling this method if this Entry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Entry) Update() *EntryUpdateOne {
	return NewEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Entry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Entry) Unwrap() *Entry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Entry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Entry) String() string {
	var builder strings.Builder
	builder.WriteString("Entry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("author_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthorID))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("entry_date=")
	builder.WriteString(_m.EntryDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("edited_last_at=")
	builder.WriteString(_m.EditedLastAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("linked_person_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.LinkedPersonIds))
	builder.WriteByte(')')
	return builder.String()
}

// Entries is a parsable slice of Entry.
type Entries []*Entry
