// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexlad/konservi/ent/entry"
	"github.com/plexlad/konservi/ent/person"
	"github.com/plexlad/konservi/ent/predicate"
	"github.com/plexlad/konservi/ent/project"
	"github.com/plexlad/konservi/ent/user"
)

// EntryUpdate is the builder for updating Entry entities.
type EntryUpdate struct {
	config
	hooks    []Hook
	mutation *EntryMutation
}

// Where appends a list predicates to the EntryUpdate builder.
func (_u *EntryUpdate) Where(ps ...predicate.Entry) *EntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *EntryUpdate) SetProjectID(v uuid.UUID) *EntryUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableProjectID(v *uuid.UUID) *EntryUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *EntryUpdate) SetAuthorID(v uuid.UUID) *EntryUpdate {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableAuthorID(v *uuid.UUID) *EntryUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *EntryUpdate) SetContent(v string) *EntryUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableContent(v *string) *EntryUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetEntryDate sets the "entry_date" field.
func (_u *EntryUpdate) SetEntryDate(v time.Time) *EntryUpdate {
	_u.mutation.SetEntryDate(v)
	return _u
}

// SetNillableEntryDate sets the "entry_date" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableEntryDate(v *time.Time) *EntryUpdate {
	if v != nil {
		_u.SetEntryDate(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EntryUpdate) SetCreatedAt(v time.Time) *EntryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableCreatedAt(v *time.Time) *EntryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetEditedLastAt sets the "edited_last_at" field.
func (_u *EntryUpdate) SetEditedLastAt(v time.Time) *EntryUpdate {
	_u.mutation.SetEditedLastAt(v)
	return _u
}

// SetNillableEditedLastAt sets the "edited_last_at" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableEditedLastAt(v *time.Time) *EntryUpdate {
	if v != nil {
		_u.SetEditedLastAt(*v)
	}
	return _u
}

// SetLinkedPersonIds sets the "linked_person_ids" field.
func (_u *EntryUpdate) SetLinkedPersonIds(v []uuid.UUID) *EntryUpdate {
	_u.mutation.SetLinkedPersonIds(v)
	return _u
}

// AppendLinkedPersonIds appends value to the "linked_person_ids" field.
func (_u *EntryUpdate) AppendLinkedPersonIds(v []uuid.UUID) *EntryUpdate {
	_u.mutation.AppendLinkedPersonIds(v)
	return _u
}

// ClearLinkedPersonIds clears the value of the "linked_person_ids" field.
func (_u *EntryUpdate) ClearLinkedPersonIds() *EntryUpdate {
	_u.mutation.ClearLinkedPersonIds()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EntryUpdate) SetProject(v *Project) *EntryUpdate {
	return _u.SetProjectID(v.ID)
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *EntryUpdate) SetAuthor(v *User) *EntryUpdate {
	return _u.SetAuthorID(v.ID)
}

// AddLinkedPersonIDs adds the "linked_people" edge to the Person entity by IDs.
func (_u *EntryUpdate) AddLinkedPersonIDs(ids ...uuid.UUID) *EntryUpdate {
	_u.mutation.AddLinkedPersonIDs(ids...)
	return _u
}

// AddLinkedPeople adds the "linked_people" edges to the Person entity.
func (_u *EntryUpdate) AddLinkedPeople(v ...*Person) *EntryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkedPersonIDs(ids...)
}

// Mutation returns the EntryMutation object of the builder.
func (_u *EntryUpdate) Mutation() *EntryMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EntryUpdate) ClearProject() *EntryUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *EntryUpdate) ClearAuthor() *EntryUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearLinkedPeople clears all "linked_people" edges to the Person entity.
func (_u *EntryUpdate) ClearLinkedPeople() *EntryUpdate {
	_u.mutation.ClearLinkedPeople()
	return _u
}

// RemoveLinkedPersonIDs removes the "linked_people" edge to Person entities by IDs.
func (_u *EntryUpdate) RemoveLinkedPersonIDs(ids ...uuid.UUID) *EntryUpdate {
	_u.mutation.RemoveLinkedPersonIDs(ids...)
	return _u
}

// RemoveLinkedPeople removes "linked_people" edges to Person entities.
func (_u *EntryUpdate) RemoveLinkedPeople(v ...*Person) *EntryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkedPersonIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntryUpdate) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := entry.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Entry.content": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Entry.project"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Entry.author"`)
	}
	return nil
}

func (_u *EntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entry.Table, entry.Columns, sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(entry.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryDate(); ok {
		_spec.SetField(entry.FieldEntryDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(entry.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EditedLastAt(); ok {
		_spec.SetField(entry.FieldEditedLastAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LinkedPersonIds(); ok {
		_spec.SetField(entry.FieldLinkedPersonIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLinkedPersonIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entry.FieldLinkedPersonIds, value)
		})
	}
	if _u.mutation.LinkedPersonIdsCleared() {
		_spec.ClearField(entry.FieldLinkedPersonIds, field.TypeJSON)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.ProjectTable,
			Columns: []string{entry.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.ProjectTable,
			Columns: []string{entry.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.AuthorTable,
			Columns: []string{entry.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.AuthorTable,
			Columns: []string{entry.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinkedPeopleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   entry.LinkedPeopleTable,
			Columns: entry.LinkedPeoplePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinkedPeopleIDs(); len(nodes) > 0 && !_u.mutation.LinkedPeopleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   entry.LinkedPeopleTable,
			Columns: entry.LinkedPeoplePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinkedPeopleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   entry.LinkedPeopleTable,
			Columns: entry.LinkedPeoplePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntryUpdateOne is the builder for updating a single Entry entity.
type EntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntryMutation
}

// SetProjectID sets the "project_id" field.
func (_u *EntryUpdateOne) SetProjectID(v uuid.UUID) *EntryUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableProjectID(v *uuid.UUID) *EntryUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *EntryUpdateOne) SetAuthorID(v uuid.UUID) *EntryUpdateOne {
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableAuthorID(v *uuid.UUID) *EntryUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *EntryUpdateOne) SetContent(v string) *EntryUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableContent(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetEntryDate sets the "entry_date" field.
func (_u *EntryUpdateOne) SetEntryDate(v time.Time) *EntryUpdateOne {
	_u.mutation.SetEntryDate(v)
	return _u
}

// SetNillableEntryDate sets the "entry_date" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableEntryDate(v *time.Time) *EntryUpdateOne {
	if v != nil {
		_u.SetEntryDate(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EntryUpdateOne) SetCreatedAt(v time.Time) *EntryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableCreatedAt(v *time.Time) *EntryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetEditedLastAt sets the "edited_last_at" field.
func (_u *EntryUpdateOne) SetEditedLastAt(v time.Time) *EntryUpdateOne {
	_u.mutation.SetEditedLastAt(v)
	return _u
}

// SetNillableEditedLastAt sets the "edited_last_at" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableEditedLastAt(v *time.Time) *EntryUpdateOne {
	if v != nil {
		_u.SetEditedLastAt(*v)
	}
	return _u
}

// SetLinkedPersonIds sets the "linked_person_ids" field.
func (_u *EntryUpdateOne) SetLinkedPersonIds(v []uuid.UUID) *EntryUpdateOne {
	_u.mutation.SetLinkedPersonIds(v)
	return _u
}

// AppendLinkedPersonIds appends value to the "linked_person_ids" field.
func (_u *EntryUpdateOne) AppendLinkedPersonIds(v []uuid.UUID) *EntryUpdateOne {
	_u.mutation.AppendLinkedPersonIds(v)
	return _u
}

// ClearLinkedPersonIds clears the value of the "linked_person_ids" field.
func (_u *EntryUpdateOne) ClearLinkedPersonIds() *EntryUpdateOne {
	_u.mutation.ClearLinkedPersonIds()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *EntryUpdateOne) SetProject(v *Project) *EntryUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *EntryUpdateOne) SetAuthor(v *User) *EntryUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// AddLinkedPersonIDs adds the "linked_people" edge to the Person entity by IDs.
func (_u *EntryUpdateOne) AddLinkedPersonIDs(ids ...uuid.UUID) *EntryUpdateOne {
	_u.mutation.AddLinkedPersonIDs(ids...)
	return _u
}

// AddLinkedPeople adds the "linked_people" edges to the Person entity.
func (_u *EntryUpdateOne) AddLinkedPeople(v ...*Person) *EntryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkedPersonIDs(ids...)
}

// Mutation returns the EntryMutation object of the builder.
func (_u *EntryUpdateOne) Mutation() *EntryMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *EntryUpdateOne) ClearProject() *EntryUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *EntryUpdateOne) ClearAuthor() *EntryUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearLinkedPeople clears all "linked_people" edges to the Person entity.
func (_u *EntryUpdateOne) ClearLinkedPeople() *EntryUpdateOne {
	_u.mutation.ClearLinkedPeople()
	return _u
}

// RemoveLinkedPersonIDs removes the "linked_people" edge to Person entities by IDs.
func (_u *EntryUpdateOne) RemoveLinkedPersonIDs(ids ...uuid.UUID) *EntryUpdateOne {
	_u.mutation.RemoveLinkedPersonIDs(ids...)
	return _u
}

// RemoveLinkedPeople removes "linked_people" edges to Person entities.
func (_u *EntryUpdateOne) RemoveLinkedPeople(v ...*Person) *EntryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkedPersonIDs(ids...)
}

// Where appends a list predicates to the EntryUpdate builder.
func (_u *EntryUpdateOne) Where(ps ...predicate.Entry) *EntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntryUpdateOne) Select(field string, fields ...string) *EntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Entry entity.
func (_u *EntryUpdateOne) Save(ctx context.Context) (*Entry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntryUpdateOne) SaveX(ctx context.Context) *Entry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntryUpdateOne) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := entry.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Entry.content": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Entry.project"`)
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Entry.author"`)
	}
	return nil
}

func (_u *EntryUpdateOne) sqlSave(ctx context.Context) (_node *Entry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entry.Table, entry.Columns, sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Entry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entry.FieldID)
		for _, f := range fields {
			if !entry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(entry.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryDate(); ok {
		_spec.SetField(entry.FieldEntryDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(entry.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EditedLastAt(); ok {
		_spec.SetField(entry.FieldEditedLastAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LinkedPersonIds(); ok {
		_spec.SetField(entry.FieldLinkedPersonIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLinkedPersonIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entry.FieldLinkedPersonIds, value)
		})
	}
	if _u.mutation.LinkedPersonIdsCleared() {
		_spec.ClearField(entry.FieldLinkedPersonIds, field.TypeJSON)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.ProjectTable,
			Columns: []string{entry.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.ProjectTable,
			Columns: []string{entry.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.AuthorTable,
			Columns: []string{entry.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.AuthorTable,
			Columns: []string{entry.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinkedPeopleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   entry.LinkedPeopleTable,
			Columns: entry.LinkedPeoplePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinkedPeopleIDs(); len(nodes) > 0 && !_u.mutation.LinkedPeopleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   entry.LinkedPeopleTable,
			Columns: entry.LinkedPeoplePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinkedPeopleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   entry.LinkedPeopleTable,
			Columns: entry.LinkedPeoplePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Entry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
