// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexlad/konservi/ent/entry"
	"github.com/plexlad/konservi/ent/person"
	"github.com/plexlad/konservi/ent/project"
	"github.com/plexlad/konservi/ent/user"
)

// EntryCreate is the builder for creating a Entry entity.
type EntryCreate struct {
	config
	mutation *EntryMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *EntryCreate) SetProjectID(v uuid.UUID) *EntryCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *EntryCreate) SetAuthorID(v uuid.UUID) *EntryCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *EntryCreate) SetContent(v string) *EntryCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetEntryDate sets the "entry_date" field.
func (_c *EntryCreate) SetEntryDate(v time.Time) *EntryCreate {
	_c.mutation.SetEntryDate(v)
	return _c
}

// SetNillableEntryDate sets the "entry_date" field if the given value is not nil.
func (_c *EntryCreate) SetNillableEntryDate(v *time.Time) *EntryCreate {
	if v != nil {
		_c.SetEntryDate(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EntryCreate) SetCreatedAt(v time.Time) *EntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EntryCreate) SetNillableCreatedAt(v *time.Time) *EntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetEditedLastAt sets the "edited_last_at" field.
func (_c *EntryCreate) SetEditedLastAt(v time.Time) *EntryCreate {
	_c.mutation.SetEditedLastAt(v)
	return _c
}

// SetNillableEditedLastAt sets the "edited_last_at" field if the given value is not nil.
func (_c *EntryCreate) SetNillableEditedLastAt(v *time.Time) *EntryCreate {
	if v != nil {
		_c.SetEditedLastAt(*v)
	}
	return _c
}

// SetLinkedPersonIds sets the "linked_person_ids" field.
func (_c *EntryCreate) SetLinkedPersonIds(v []uuid.UUID) *EntryCreate {
	_c.mutation.SetLinkedPersonIds(v)
	return _c
}

// SetID sets the "id" field.
func (_c *EntryCreate) SetID(v uuid.UUID) *EntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EntryCreate) SetNillableID(v *uuid.UUID) *EntryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *EntryCreate) SetProject(v *Project) *EntryCreate {
	return _c.SetProjectID(v.ID)
}

// SetAuthor sets the "author" edge to the User entity.
func (_c *EntryCreate) SetAuthor(v *User) *EntryCreate {
	return _c.SetAuthorID(v.ID)
}

// AddLinkedPersonIDs adds the "linked_people" edge to the Person entity by IDs.
func (_c *EntryCreate) AddLinkedPersonIDs(ids ...uuid.UUID) *EntryCreate {
	_c.mutation.AddLinkedPersonIDs(ids...)
	return _c
}

// AddLinkedPeople adds the "linked_people" edges to the Person entity.
func (_c *EntryCreate) AddLinkedPeople(v ...*Person) *EntryCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLinkedPersonIDs(ids...)
}

// Mutation returns the EntryMutation object of the builder.
func (_c *EntryCreate) Mutation() *EntryMutation {
	return _c.mutation
}

// Save creates the Entry in the database.
func (_c *EntryCreate) Save(ctx context.Context) (*Entry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntryCreate) SaveX(ctx context.Context) *Entry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntryCreate) defaults() {
	if _, ok := _c.mutation.EntryDate(); !ok {
		v := entry.DefaultEntryDate()
		_c.mutation.SetEntryDate(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := entry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.EditedLastAt(); !ok {
		v := entry.DefaultEditedLastAt()
		_c.mutation.SetEditedLastAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := entry.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntryCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Entry.project_id"`)}
	}
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "Entry.author_id"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Entry.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := entry.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Entry.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntryDate(); !ok {
		return &ValidationError{Name: "entry_date", err: errors.New(`ent: missing required field "Entry.entry_date"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Entry.created_at"`)}
	}
	if _, ok := _c.mutation.EditedLastAt(); !ok {
		return &ValidationError{Name: "edited_last_at", err: errors.New(`ent: missing required field "Entry.edited_last_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Entry.project"`)}
	}
	if len(_c.mutation.AuthorIDs()) == 0 {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required edge "Entry.author"`)}
	}
	return nil
}

func (_c *EntryCreate) sqlSave(ctx context.Context) (*Entry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntryCreate) createSpec() (*Entry, *sqlgraph.CreateSpec) {
	var (
		_node = &Entry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entry.Table, sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(entry.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.EntryDate(); ok {
		_spec.SetField(entry.FieldEntryDate, field.TypeTime, value)
		_node.EntryDate = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.EditedLastAt(); ok {
		_spec.SetField(entry.FieldEditedLastAt, field.TypeTime, value)
		_node.EditedLastAt = value
	}
	if value, ok := _c.mutation.LinkedPersonIds(); ok {
		_spec.SetField(entry.FieldLinkedPersonIds, field.TypeJSON, value)
		_node.LinkedPersonIds = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.ProjectTable,
			Columns: []string{entry.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.AuthorTable,
			Columns: []string{entry.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuthorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LinkedPeopleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   entry.LinkedPeopleTable,
			Columns: entry.LinkedPeoplePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EntryCreateBulk is the builder for creating many Entry entities in bulk.
type EntryCreateBulk struct {
	config
	err      error
	builders []*EntryCreate
}

// Save creates the Entry entities in the database.
func (_c *EntryCreateBulk) Save(ctx context.Context) ([]*Entry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Entry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntryCreateBulk) SaveX(ctx context.Context) []*Entry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
