// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexlad/konservi/ent/family"
	"github.com/plexlad/konservi/ent/person"
	"github.com/plexlad/konservi/ent/project"
)

// Family is the model entity for the Family schema.
type Family struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// GEDCOM UID - durable identifier across cycles
	UID string `json:"uid,omitempty"`
	// GEDCOM EXID - external reference
	ExternalID string `json:"external_id,omitempty"`
	// HusbandID holds the value of the "husband_id" field.
	HusbandID uuid.UUID `json:"husband_id,omitempty"`
	// WifeID holds the value of the "wife_id" field.
	WifeID uuid.UUID `json:"wife_id,omitempty"`
	// Additional spouses for polygamous families
	SpouseIds []uuid.UUID `json:"spouse_ids,omitempty"`
	// MarriageDate holds the value of the "marriage_date" field.
	MarriageDate time.Time `json:"marriage_date,omitempty"`
	// MarriagePlace holds the value of the "marriage_place" field.
	MarriagePlace string `json:"marriage_place,omitempty"`
	// MarriageCalendar holds the value of the "marriage_calendar" field.
	MarriageCalendar string `json:"marriage_calendar,omitempty"`
	// MARB - public notice of intent to marry
	MarriageBannsDate time.Time `json:"marriage_banns_date,omitempty"`
	// DivorceDate holds the value of the "divorce_date" field.
	DivorceDate time.Time `json:"divorce_date,omitempty"`
	// AnnulmentDate holds the value of the "annulment_date" field.
	AnnulmentDate time.Time `json:"annulment_date,omitempty"`
	// MarriageType holds the value of the "marriage_type" field.
	MarriageType string `json:"marriage_type,omitempty"`
	// ChildrenIds holds the value of the "children_ids" field.
	ChildrenIds []uuid.UUID `json:"children_ids,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// Sources holds the value of the "sources" field.
	Sources []map[string]interface{} `json:"sources,omitempty"`
	// SharedNotes holds the value of the "shared_notes" field.
	SharedNotes []map[string]interface{} `json:"shared_notes,omitempty"`
	// RESN tag support for sensitive data
	Privacy family.Privacy `json:"privacy,omitempty"`
	// UUID of User who created this record
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// UUID of User who last updated this record
	UpdatedBy uuid.UUID `json:"updated_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FamilyQuery when eager-loading is set.
	Edges        FamilyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FamilyEdges holds the relations/edges for other nodes in the graph.
type FamilyEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Husband holds the value of the husband edge.
	Husband *Person `json:"husband,omitempty"`
	// Wife holds the value of the wife edge.
	Wife *Person `json:"wife,omitempty"`
	// Additional spouses linked via ASSO or multiple FAMs
	Spouses []*Person `json:"spouses,omitempty"`
	// Children holds the value of the children edge.
	Children []*Person `json:"children,omitempty"`
	// Entries holds the value of the entries edge.
	Entries []*Entry `json:"entries,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FamilyEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// HusbandOrErr returns the Husband value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FamilyEdges) HusbandOrErr() (*Person, error) {
	if e.Husband != nil {
		return e.Husband, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: person.Label}
	}
	return nil, &NotLoadedError{edge: "husband"}
}

// WifeOrErr returns the Wife value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FamilyEdges) WifeOrErr() (*Person, error) {
	if e.Wife != nil {
		return e.Wife, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: person.Label}
	}
	return nil, &NotLoadedError{edge: "wife"}
}

// SpousesOrErr returns the Spouses value or an error if the edge
// was not loaded in eager-loading.
func (e FamilyEdges) SpousesOrErr() ([]*Person, error) {
	if e.loadedTypes[3] {
		return e.Spouses, nil
	}
	return nil, &NotLoadedError{edge: "spouses"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e FamilyEdges) ChildrenOrErr() ([]*Person, error) {
	if e.loadedTypes[4] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// EntriesOrErr returns the Entries value or an error if the edge
// was not loaded in eager-loading.
func (e FamilyEdges) EntriesOrErr() ([]*Entry, error) {
	if e.loadedTypes[5] {
		return e.Entries, nil
	}
	return nil, &NotLoadedError{edge: "entries"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Family) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case family.FieldSpouseIds, family.FieldChildrenIds, family.FieldSources, family.FieldSharedNotes:
			values[i] = new([]byte)
		case family.FieldUID, family.FieldExternalID, family.FieldMarriagePlace, family.FieldMarriageCalendar, family.FieldMarriageType, family.FieldNotes, family.FieldPrivacy:
			values[i] = new(sql.NullString)
		case family.FieldMarriageDate, family.FieldMarriageBannsDate, family.FieldDivorceDate, family.FieldAnnulmentDate, family.FieldCreatedAt, family.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case family.FieldID, family.FieldProjectID, family.FieldHusbandID, family.FieldWifeID, family.FieldCreatedBy, family.FieldUpdatedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Family fields.
func (_m *Family) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case family.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case family.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case family.FieldUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				_m.UID = value.String
			}
		case family.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = value.String
			}
		case family.FieldHusbandID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field husband_id", values[i])
			} else if value != nil {
				_m.HusbandID = *value
			}
		case family.FieldWifeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field wife_id", values[i])
			} else if value != nil {
				_m.WifeID = *value
			}
		case family.FieldSpouseIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field spouse_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SpouseIds); err != nil {
					return fmt.Errorf("unmarshal field spouse_ids: %w", err)
				}
			}
		case family.FieldMarriageDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field marriage_date", values[i])
			} else if value.Valid {
				_m.MarriageDate = value.Time
			}
		case family.FieldMarriagePlace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field marriage_place", values[i])
			} else if value.Valid {
				_m.MarriagePlace = value.String
			}
		case family.FieldMarriageCalendar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field marriage_calendar", values[i])
			} else if value.Valid {
				_m.MarriageCalendar = value.String
			}
		case family.FieldMarriageBannsDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field marriage_banns_date", values[i])
			} else if value.Valid {
				_m.MarriageBannsDate = value.Time
			}
		case family.FieldDivorceDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field divorce_date", values[i])
			} else if value.Valid {
				_m.DivorceDate = value.Time
			}
		case family.FieldAnnulmentDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field annulment_date", values[i])
			} else if value.Valid {
				_m.AnnulmentDate = value.Time
			}
		case family.FieldMarriageType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field marriage_type", values[i])
			} else if value.Valid {
				_m.MarriageType = value.String
			}
		case family.FieldChildrenIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field children_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ChildrenIds); err != nil {
					return fmt.Errorf("unmarshal field children_ids: %w", err)
				}
			}
		case family.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case family.FieldSources:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field sources", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Sources); err != nil {
					return fmt.Errorf("unmarshal field sources: %w", err)
				}
			}
		case family.FieldSharedNotes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field shared_notes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SharedNotes); err != nil {
					return fmt.Errorf("unmarshal field shared_notes: %w", err)
				}
			}
		case family.FieldPrivacy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field privacy", values[i])
			} else if value.Valid {
				_m.Privacy = family.Privacy(value.String)
			}
		case family.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				_m.CreatedBy = *value
			}
		case family.FieldUpdatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value != nil {
				_m.UpdatedBy = *value
			}
		case family.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case family.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Family.
// This includes values selected through modifiers, order, etc.
func (_m *Family) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Family entity.
func (_m *Family) QueryProject() *ProjectQuery {
	return NewFamilyClient(_m.config).QueryProject(_m)
}

// QueryHusband queries the "husband" edge of the Family entity.
func (_m *Family) QueryHusband() *PersonQuery {
	return NewFamilyClient(_m.config).QueryHusband(_m)
}

// QueryWife queries the "wife" edge of the Family entity.
func (_m *Family) QueryWife() *PersonQuery {
	return NewFamilyClient(_m.config).QueryWife(_m)
}

// QuerySpouses queries the "spouses" edge of the Family entity.
func (_m *Family) QuerySpouses() *PersonQuery {
	return NewFamilyClient(_m.config).QuerySpouses(_m)
}

// QueryChildren queries the "children" edge of the Family entity.
func (_m *Family) QueryChildren() *PersonQuery {
	return NewFamilyClient(_m.config).QueryChildren(_m)
}

// QueryEntries queries the "entries" edge of the Family entity.
func (_m *Family) QueryEntries() *EntryQuery {
	return NewFamilyClient(_m.config).QueryEntries(_m)
}

// Update returns a builder for updating this Family.
// Note that you need to call Family.Unwrap() before calling this method if this Family
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Family) Update() *FamilyUpdateOne {
	return NewFamilyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Family entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Family) Unwrap() *Family {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Family is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Family) String() string {
	var builder strings.Builder
	builder.WriteString("Family(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("uid=")
	builder.WriteString(_m.UID)
	builder.WriteString(", ")
	builder.WriteString("external_id=")
	builder.WriteString(_m.ExternalID)
	builder.WriteString(", ")
	builder.WriteString("husband_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HusbandID))
	builder.WriteString(", ")
	builder.WriteString("wife_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WifeID))
	builder.WriteString(", ")
	builder.WriteString("spouse_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.SpouseIds))
	builder.WriteString(", ")
	builder.WriteString("marriage_date=")
	builder.WriteString(_m.MarriageDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("marriage_place=")
	builder.WriteString(_m.MarriagePlace)
	builder.WriteString(", ")
	builder.WriteString("marriage_calendar=")
	builder.WriteString(_m.MarriageCalendar)
	builder.WriteString(", ")
	builder.WriteString("marriage_banns_date=")
	builder.WriteString(_m.MarriageBannsDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("divorce_date=")
	builder.WriteString(_m.DivorceDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("annulment_date=")
	builder.WriteString(_m.AnnulmentDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("marriage_type=")
	builder.WriteString(_m.MarriageType)
	builder.WriteString(", ")
	builder.WriteString("children_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChildrenIds))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("sources=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sources))
	builder.WriteString(", ")
	builder.WriteString("shared_notes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SharedNotes))
	builder.WriteString(", ")
	builder.WriteString("privacy=")
	builder.WriteString(fmt.Sprintf("%v", _m.Privacy))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Families is a parsable slice of Family.
type Families []*Family
