// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexlad/konservi/ent/entry"
	"github.com/plexlad/konservi/ent/family"
	"github.com/plexlad/konservi/ent/person"
	"github.com/plexlad/konservi/ent/project"
)

// FamilyCreate is the builder for creating a Family entity.
type FamilyCreate struct {
	config
	mutation *FamilyMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *FamilyCreate) SetProjectID(v uuid.UUID) *FamilyCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetUID sets the "uid" field.
func (_c *FamilyCreate) SetUID(v string) *FamilyCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableUID(v *string) *FamilyCreate {
	if v != nil {
		_c.SetUID(*v)
	}
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *FamilyCreate) SetExternalID(v string) *FamilyCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableExternalID(v *string) *FamilyCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetHusbandID sets the "husband_id" field.
func (_c *FamilyCreate) SetHusbandID(v uuid.UUID) *FamilyCreate {
	_c.mutation.SetHusbandID(v)
	return _c
}

// SetNillableHusbandID sets the "husband_id" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableHusbandID(v *uuid.UUID) *FamilyCreate {
	if v != nil {
		_c.SetHusbandID(*v)
	}
	return _c
}

// SetWifeID sets the "wife_id" field.
func (_c *FamilyCreate) SetWifeID(v uuid.UUID) *FamilyCreate {
	_c.mutation.SetWifeID(v)
	return _c
}

// SetNillableWifeID sets the "wife_id" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableWifeID(v *uuid.UUID) *FamilyCreate {
	if v != nil {
		_c.SetWifeID(*v)
	}
	return _c
}

// SetSpouseIds sets the "spouse_ids" field.
func (_c *FamilyCreate) SetSpouseIds(v []uuid.UUID) *FamilyCreate {
	_c.mutation.SetSpouseIds(v)
	return _c
}

// SetMarriageDate sets the "marriage_date" field.
func (_c *FamilyCreate) SetMarriageDate(v time.Time) *FamilyCreate {
	_c.mutation.SetMarriageDate(v)
	return _c
}

// SetNillableMarriageDate sets the "marriage_date" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableMarriageDate(v *time.Time) *FamilyCreate {
	if v != nil {
		_c.SetMarriageDate(*v)
	}
	return _c
}

// SetMarriagePlace sets the "marriage_place" field.
func (_c *FamilyCreate) SetMarriagePlace(v string) *FamilyCreate {
	_c.mutation.SetMarriagePlace(v)
	return _c
}

// SetNillableMarriagePlace sets the "marriage_place" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableMarriagePlace(v *string) *FamilyCreate {
	if v != nil {
		_c.SetMarriagePlace(*v)
	}
	return _c
}

// SetMarriageCalendar sets the "marriage_calendar" field.
func (_c *FamilyCreate) SetMarriageCalendar(v string) *FamilyCreate {
	_c.mutation.SetMarriageCalendar(v)
	return _c
}

// SetNillableMarriageCalendar sets the "marriage_calendar" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableMarriageCalendar(v *string) *FamilyCreate {
	if v != nil {
		_c.SetMarriageCalendar(*v)
	}
	return _c
}

// SetMarriageBannsDate sets the "marriage_banns_date" field.
func (_c *FamilyCreate) SetMarriageBannsDate(v time.Time) *FamilyCreate {
	_c.mutation.SetMarriageBannsDate(v)
	return _c
}

// SetNillableMarriageBannsDate sets the "marriage_banns_date" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableMarriageBannsDate(v *time.Time) *FamilyCreate {
	if v != nil {
		_c.SetMarriageBannsDate(*v)
	}
	return _c
}

// SetDivorceDate sets the "divorce_date" field.
func (_c *FamilyCreate) SetDivorceDate(v time.Time) *FamilyCreate {
	_c.mutation.SetDivorceDate(v)
	return _c
}

// SetNillableDivorceDate sets the "divorce_date" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableDivorceDate(v *time.Time) *FamilyCreate {
	if v != nil {
		_c.SetDivorceDate(*v)
	}
	return _c
}

// SetAnnulmentDate sets the "annulment_date" field.
func (_c *FamilyCreate) SetAnnulmentDate(v time.Time) *FamilyCreate {
	_c.mutation.SetAnnulmentDate(v)
	return _c
}

// SetNillableAnnulmentDate sets the "annulment_date" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableAnnulmentDate(v *time.Time) *FamilyCreate {
	if v != nil {
		_c.SetAnnulmentDate(*v)
	}
	return _c
}

// SetMarriageType sets the "marriage_type" field.
func (_c *FamilyCreate) SetMarriageType(v string) *FamilyCreate {
	_c.mutation.SetMarriageType(v)
	return _c
}

// SetNillableMarriageType sets the "marriage_type" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableMarriageType(v *string) *FamilyCreate {
	if v != nil {
		_c.SetMarriageType(*v)
	}
	return _c
}

// SetChildrenIds sets the "children_ids" field.
func (_c *FamilyCreate) SetChildrenIds(v []uuid.UUID) *FamilyCreate {
	_c.mutation.SetChildrenIds(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *FamilyCreate) SetNotes(v string) *FamilyCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableNotes(v *string) *FamilyCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetSources sets the "sources" field.
func (_c *FamilyCreate) SetSources(v []map[string]interface{}) *FamilyCreate {
	_c.mutation.SetSources(v)
	return _c
}

// SetSharedNotes sets the "shared_notes" field.
func (_c *FamilyCreate) SetSharedNotes(v []map[string]interface{}) *FamilyCreate {
	_c.mutation.SetSharedNotes(v)
	return _c
}

// SetPrivacy sets the "privacy" field.
func (_c *FamilyCreate) SetPrivacy(v family.Privacy) *FamilyCreate {
	_c.mutation.SetPrivacy(v)
	return _c
}

// SetNillablePrivacy sets the "privacy" field if the given value is not nil.
func (_c *FamilyCreate) SetNillablePrivacy(v *family.Privacy) *FamilyCreate {
	if v != nil {
		_c.SetPrivacy(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *FamilyCreate) SetCreatedBy(v uuid.UUID) *FamilyCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableCreatedBy(v *uuid.UUID) *FamilyCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *FamilyCreate) SetUpdatedBy(v uuid.UUID) *FamilyCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableUpdatedBy(v *uuid.UUID) *FamilyCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FamilyCreate) SetCreatedAt(v time.Time) *FamilyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableCreatedAt(v *time.Time) *FamilyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FamilyCreate) SetUpdatedAt(v time.Time) *FamilyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableUpdatedAt(v *time.Time) *FamilyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FamilyCreate) SetID(v uuid.UUID) *FamilyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FamilyCreate) SetNillableID(v *uuid.UUID) *FamilyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *FamilyCreate) SetProject(v *Project) *FamilyCreate {
	return _c.SetProjectID(v.ID)
}

// SetHusband sets the "husband" edge to the Person entity.
func (_c *FamilyCreate) SetHusband(v *Person) *FamilyCreate {
	return _c.SetHusbandID(v.ID)
}

// SetWife sets the "wife" edge to the Person entity.
func (_c *FamilyCreate) SetWife(v *Person) *FamilyCreate {
	return _c.SetWifeID(v.ID)
}

// AddSpouseIDs adds the "spouses" edge to the Person entity by IDs.
func (_c *FamilyCreate) AddSpouseIDs(ids ...uuid.UUID) *FamilyCreate {
	_c.mutation.AddSpouseIDs(ids...)
	return _c
}

// AddSpouses adds the "spouses" edges to the Person entity.
func (_c *FamilyCreate) AddSpouses(v ...*Person) *FamilyCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSpouseIDs(ids...)
}

// AddChildIDs adds the "children" edge to the Person entity by IDs.
func (_c *FamilyCreate) AddChildIDs(ids ...uuid.UUID) *FamilyCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Person entity.
func (_c *FamilyCreate) AddChildren(v ...*Person) *FamilyCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddEntryIDs adds the "entries" edge to the Entry entity by IDs.
func (_c *FamilyCreate) AddEntryIDs(ids ...uuid.UUID) *FamilyCreate {
	_c.mutation.AddEntryIDs(ids...)
	return _c
}

// AddEntries adds the "entries" edges to the Entry entity.
func (_c *FamilyCreate) AddEntries(v ...*Entry) *FamilyCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEntryIDs(ids...)
}

// Mutation returns the FamilyMutation object of the builder.
func (_c *FamilyCreate) Mutation() *FamilyMutation {
	return _c.mutation
}

// Save creates the Family in the database.
func (_c *FamilyCreate) Save(ctx context.Context) (*Family, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FamilyCreate) SaveX(ctx context.Context) *Family {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FamilyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FamilyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FamilyCreate) defaults() {
	if _, ok := _c.mutation.Privacy(); !ok {
		v := family.DefaultPrivacy
		_c.mutation.SetPrivacy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := family.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := family.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := family.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FamilyCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Family.project_id"`)}
	}
	if _, ok := _c.mutation.Privacy(); !ok {
		return &ValidationError{Name: "privacy", err: errors.New(`ent: missing required field "Family.privacy"`)}
	}
	if v, ok := _c.mutation.Privacy(); ok {
		if err := family.PrivacyValidator(v); err != nil {
			return &ValidationError{Name: "privacy", err: fmt.Errorf(`ent: validator failed for field "Family.privacy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Family.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Family.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Family.project"`)}
	}
	return nil
}

func (_c *FamilyCreate) sqlSave(ctx context.Context) (*Family, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FamilyCreate) createSpec() (*Family, *sqlgraph.CreateSpec) {
	var (
		_node = &Family{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(family.Table, sqlgraph.NewFieldSpec(family.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(family.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(family.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.SpouseIds(); ok {
		_spec.SetField(family.FieldSpouseIds, field.TypeJSON, value)
		_node.SpouseIds = value
	}
	if value, ok := _c.mutation.MarriageDate(); ok {
		_spec.SetField(family.FieldMarriageDate, field.TypeTime, value)
		_node.MarriageDate = value
	}
	if value, ok := _c.mutation.MarriagePlace(); ok {
		_spec.SetField(family.FieldMarriagePlace, field.TypeString, value)
		_node.MarriagePlace = value
	}
	if value, ok := _c.mutation.MarriageCalendar(); ok {
		_spec.SetField(family.FieldMarriageCalendar, field.TypeString, value)
		_node.MarriageCalendar = value
	}
	if value, ok := _c.mutation.MarriageBannsDate(); ok {
		_spec.SetField(family.FieldMarriageBannsDate, field.TypeTime, value)
		_node.MarriageBannsDate = value
	}
	if value, ok := _c.mutation.DivorceDate(); ok {
		_spec.SetField(family.FieldDivorceDate, field.TypeTime, value)
		_node.DivorceDate = value
	}
	if value, ok := _c.mutation.AnnulmentDate(); ok {
		_spec.SetField(family.FieldAnnulmentDate, field.TypeTime, value)
		_node.AnnulmentDate = value
	}
	if value, ok := _c.mutation.MarriageType(); ok {
		_spec.SetField(family.FieldMarriageType, field.TypeString, value)
		_node.MarriageType = value
	}
	if value, ok := _c.mutation.ChildrenIds(); ok {
		_spec.SetField(family.FieldChildrenIds, field.TypeJSON, value)
		_node.ChildrenIds = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(family.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.Sources(); ok {
		_spec.SetField(family.FieldSources, field.TypeJSON, value)
		_node.Sources = value
	}
	if value, ok := _c.mutation.SharedNotes(); ok {
		_spec.SetField(family.FieldSharedNotes, field.TypeJSON, value)
		_node.SharedNotes = value
	}
	if value, ok := _c.mutation.Privacy(); ok {
		_spec.SetField(family.FieldPrivacy, field.TypeEnum, value)
		_node.Privacy = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(family.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(family.FieldUpdatedBy, field.TypeUUID, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(family.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(family.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   family.ProjectTable,
			Columns: []string{family.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.HusbandIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   family.HusbandTable,
			Columns: []string{family.HusbandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HusbandID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WifeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   family.WifeTable,
			Columns: []string{family.WifeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WifeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SpousesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.SpousesTable,
			Columns: []string{family.SpousesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   family.ChildrenTable,
			Columns: family.ChildrenPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   family.EntriesTable,
			Columns: []string{family.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FamilyCreateBulk is the builder for creating many Family entities in bulk.
type FamilyCreateBulk struct {
	config
	err      error
	builders []*FamilyCreate
}

// Save creates the Family entities in the database.
func (_c *FamilyCreateBulk) Save(ctx context.Context) ([]*Family, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Family, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FamilyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FamilyCreateBulk) SaveX(ctx context.Context) []*Family {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FamilyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FamilyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
