// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/plexlad/konservi/ent/person"
	"github.com/plexlad/konservi/ent/project"
)

// Person is the model entity for the Person schema.
type Person struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// External identifier (EXID tag)
	ExternalID string `json:"external_id,omitempty"`
	// PrimaryName holds the value of the "primary_name" field.
	PrimaryName string `json:"primary_name,omitempty"`
	// All name variants with LANG and TRAN
	Names []map[string]interface{} `json:"names,omitempty"`
	// Rufname/call name
	PreferredName string `json:"preferred_name,omitempty"`
	// MaidenName holds the value of the "maiden_name" field.
	MaidenName string `json:"maiden_name,omitempty"`
	// Sex holds the value of the "sex" field.
	Sex person.Sex `json:"sex,omitempty"`
	// BirthDate holds the value of the "birth_date" field.
	BirthDate time.Time `json:"birth_date,omitempty"`
	// For BET/AND dates
	BirthDateApprox string `json:"birth_date_approx,omitempty"`
	// BirthPlace holds the value of the "birth_place" field.
	BirthPlace string `json:"birth_place,omitempty"`
	// BirthPlaceJurisdiction holds the value of the "birth_place_jurisdiction" field.
	BirthPlaceJurisdiction []string `json:"birth_place_jurisdiction,omitempty"`
	// DeathDate holds the value of the "death_date" field.
	DeathDate time.Time `json:"death_date,omitempty"`
	// DeathPlace holds the value of the "death_place" field.
	DeathPlace string `json:"death_place,omitempty"`
	// DeathCause holds the value of the "death_cause" field.
	DeathCause string `json:"death_cause,omitempty"`
	// DeathDetails holds the value of the "death_details" field.
	DeathDetails []map[string]interface{} `json:"death_details,omitempty"`
	// BurialPlace holds the value of the "burial_place" field.
	BurialPlace string `json:"burial_place,omitempty"`
	// BurialDate holds the value of the "burial_date" field.
	BurialDate time.Time `json:"burial_date,omitempty"`
	// Occupation holds the value of the "occupation" field.
	Occupation string `json:"occupation,omitempty"`
	// OccupationDetails holds the value of the "occupation_details" field.
	OccupationDetails []map[string]interface{} `json:"occupation_details,omitempty"`
	// Education holds the value of the "education" field.
	Education string `json:"education,omitempty"`
	// Religion holds the value of the "religion" field.
	Religion string `json:"religion,omitempty"`
	// Nationality holds the value of the "nationality" field.
	Nationality string `json:"nationality,omitempty"`
	// Ethnicity holds the value of the "ethnicity" field.
	Ethnicity string `json:"ethnicity,omitempty"`
	// Aliases holds the value of the "aliases" field.
	Aliases []string `json:"aliases,omitempty"`
	// Nicknames holds the value of the "nicknames" field.
	Nicknames []string `json:"nicknames,omitempty"`
	// Titles holds the value of the "titles" field.
	Titles []string `json:"titles,omitempty"`
	// Height holds the value of the "height" field.
	Height map[string]interface{} `json:"height,omitempty"`
	// Weight holds the value of the "weight" field.
	Weight map[string]interface{} `json:"weight,omitempty"`
	// BloodType holds the value of the "blood_type" field.
	BloodType map[string]interface{} `json:"blood_type,omitempty"`
	// MedicalConditions holds the value of the "medical_conditions" field.
	MedicalConditions []map[string]interface{} `json:"medical_conditions,omitempty"`
	// GeneticMarkers holds the value of the "genetic_markers" field.
	GeneticMarkers []map[string]interface{} `json:"genetic_markers,omitempty"`
	// DnaMatches holds the value of the "dna_matches" field.
	DnaMatches []map[string]interface{} `json:"dna_matches,omitempty"`
	// Photos holds the value of the "photos" field.
	Photos []map[string]interface{} `json:"photos,omitempty"`
	// Documents holds the value of the "documents" field.
	Documents []map[string]interface{} `json:"documents,omitempty"`
	// Events holds the value of the "events" field.
	Events []map[string]interface{} `json:"events,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// Sources holds the value of the "sources" field.
	Sources []map[string]interface{} `json:"sources,omitempty"`
	// SharedNotes holds the value of the "shared_notes" field.
	SharedNotes []map[string]interface{} `json:"shared_notes,omitempty"`
	// Media holds the value of the "media" field.
	Media []map[string]interface{} `json:"media,omitempty"`
	// RESN tag support
	Privacy person.Privacy `json:"privacy,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// FatherID holds the value of the "father_id" field.
	FatherID uuid.UUID `json:"father_id,omitempty"`
	// MotherID holds the value of the "mother_id" field.
	MotherID uuid.UUID `json:"mother_id,omitempty"`
	// UUID of User who created this record
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// UUID of User who last updated this record
	UpdatedBy uuid.UUID `json:"updated_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PersonQuery when eager-loading is set.
	Edges          PersonEdges `json:"edges"`
	family_spouses *uuid.UUID
	selectValues   sql.SelectValues
}

// PersonEdges holds the relations/edges for other nodes in the graph.
type PersonEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Father holds the value of the father edge.
	Father *Person `json:"father,omitempty"`
	// Mother holds the value of the mother edge.
	Mother *Person `json:"mother,omitempty"`
	// Children holds the value of the children edge.
	Children []*Person `json:"children,omitempty"`
	// Spouses holds the value of the spouses edge.
	Spouses []*Person `json:"spouses,omitempty"`
	// Entries holds the value of the entries edge.
	Entries []*Entry `json:"entries,omitempty"`
	// LinkedEntries holds the value of the linked_entries edge.
	LinkedEntries []*Entry `json:"linked_entries,omitempty"`
	// Relatives holds the value of the relatives edge.
	Relatives []*Person `json:"relatives,omitempty"`
	// Associations holds the value of the associations edge.
	Associations []*Person `json:"associations,omitempty"`
	// FamiliesAsHusband holds the value of the families_as_husband edge.
	FamiliesAsHusband []*Family `json:"families_as_husband,omitempty"`
	// FamiliesAsWife holds the value of the families_as_wife edge.
	FamiliesAsWife []*Family `json:"families_as_wife,omitempty"`
	// FamiliesAsChild holds the value of the families_as_child edge.
	FamiliesAsChild []*Family `json:"families_as_child,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [12]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PersonEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// FatherOrErr returns the Father value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PersonEdges) FatherOrErr() (*Person, error) {
	if e.Father != nil {
		return e.Father, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: person.Label}
	}
	return nil, &NotLoadedError{edge: "father"}
}

// MotherOrErr returns the Mother value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PersonEdges) MotherOrErr() (*Person, error) {
	if e.Mother != nil {
		return e.Mother, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: person.Label}
	}
	return nil, &NotLoadedError{edge: "mother"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e PersonEdges) ChildrenOrErr() ([]*Person, error) {
	if e.loadedTypes[3] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// SpousesOrErr returns the Spouses value or an error if the edge
// was not loaded in eager-loading.
func (e PersonEdges) SpousesOrErr() ([]*Person, error) {
	if e.loadedTypes[4] {
		return e.Spouses, nil
	}
	return nil, &NotLoadedError{edge: "spouses"}
}

// EntriesOrErr returns the Entries value or an error if the edge
// was not loaded in eager-loading.
func (e PersonEdges) EntriesOrErr() ([]*Entry, error) {
	if e.loadedTypes[5] {
		return e.Entries, nil
	}
	return nil, &NotLoadedError{edge: "entries"}
}

// LinkedEntriesOrErr returns the LinkedEntries value or an error if the edge
// was not loaded in eager-loading.
func (e PersonEdges) LinkedEntriesOrErr() ([]*Entry, error) {
	if e.loadedTypes[6] {
		return e.LinkedEntries, nil
	}
	return nil, &NotLoadedError{edge: "linked_entries"}
}

// RelativesOrErr returns the Relatives value or an error if the edge
// was not loaded in eager-loading.
func (e PersonEdges) RelativesOrErr() ([]*Person, error) {
	if e.loadedTypes[7] {
		return e.Relatives, nil
	}
	return nil, &NotLoadedError{edge: "relatives"}
}

// AssociationsOrErr returns the Associations value or an error if the edge
// was not loaded in eager-loading.
func (e PersonEdges) AssociationsOrErr() ([]*Person, error) {
	if e.loadedTypes[8] {
		return e.Associations, nil
	}
	return nil, &NotLoadedError{edge: "associations"}
}

// FamiliesAsHusbandOrErr returns the FamiliesAsHusband value or an error if the edge
// was not loaded in eager-loading.
func (e PersonEdges) FamiliesAsHusbandOrErr() ([]*Family, error) {
	if e.loadedTypes[9] {
		return e.FamiliesAsHusband, nil
	}
	return nil, &NotLoadedError{edge: "families_as_husband"}
}

// FamiliesAsWifeOrErr returns the FamiliesAsWife value or an error if the edge
// was not loaded in eager-loading.
func (e PersonEdges) FamiliesAsWifeOrErr() ([]*Family, error) {
	if e.loadedTypes[10] {
		return e.FamiliesAsWife, nil
	}
	return nil, &NotLoadedError{edge: "families_as_wife"}
}

// FamiliesAsChildOrErr returns the FamiliesAsChild value or an error if the edge
// was not loaded in eager-loading.
func (e PersonEdges) FamiliesAsChildOrErr() ([]*Family, error) {
	if e.loadedTypes[11] {
		return e.FamiliesAsChild, nil
	}
	return nil, &NotLoadedError{edge: "families_as_child"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Person) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case person.FieldNames, person.FieldBirthPlaceJurisdiction, person.FieldDeathDetails, person.FieldOccupationDetails, person.FieldAliases, person.FieldNicknames, person.FieldTitles, person.FieldHeight, person.FieldWeight, person.FieldBloodType, person.FieldMedicalConditions, person.FieldGeneticMarkers, person.FieldDnaMatches, person.FieldPhotos, person.FieldDocuments, person.FieldEvents, person.FieldSources, person.FieldSharedNotes, person.FieldMedia:
			values[i] = new([]byte)
		case person.FieldExternalID, person.FieldPrimaryName, person.FieldPreferredName, person.FieldMaidenName, person.FieldSex, person.FieldBirthDateApprox, person.FieldBirthPlace, person.FieldDeathPlace, person.FieldDeathCause, person.FieldBurialPlace, person.FieldOccupation, person.FieldEducation, person.FieldReligion, person.FieldNationality, person.FieldEthnicity, person.FieldNotes, person.FieldPrivacy:
			values[i] = new(sql.NullString)
		case person.FieldBirthDate, person.FieldDeathDate, person.FieldBurialDate, person.FieldCreatedAt, person.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case person.FieldID, person.FieldProjectID, person.FieldFatherID, person.FieldMotherID, person.FieldCreatedBy, person.FieldUpdatedBy:
			values[i] = new(uuid.UUID)
		case person.ForeignKeys[0]: // family_spouses
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Person fields.
func (_m *Person) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case person.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case person.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case person.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = value.String
			}
		case person.FieldPrimaryName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field primary_name", values[i])
			} else if value.Valid {
				_m.PrimaryName = value.String
			}
		case person.FieldNames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field names", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Names); err != nil {
					return fmt.Errorf("unmarshal field names: %w", err)
				}
			}
		case person.FieldPreferredName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preferred_name", values[i])
			} else if value.Valid {
				_m.PreferredName = value.String
			}
		case person.FieldMaidenName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field maiden_name", values[i])
			} else if value.Valid {
				_m.MaidenName = value.String
			}
		case person.FieldSex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sex", values[i])
			} else if value.Valid {
				_m.Sex = person.Sex(value.String)
			}
		case person.FieldBirthDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field birth_date", values[i])
			} else if value.Valid {
				_m.BirthDate = value.Time
			}
		case person.FieldBirthDateApprox:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field birth_date_approx", values[i])
			} else if value.Valid {
				_m.BirthDateApprox = value.String
			}
		case person.FieldBirthPlace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field birth_place", values[i])
			} else if value.Valid {
				_m.BirthPlace = value.String
			}
		case person.FieldBirthPlaceJurisdiction:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field birth_place_jurisdiction", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BirthPlaceJurisdiction); err != nil {
					return fmt.Errorf("unmarshal field birth_place_jurisdiction: %w", err)
				}
			}
		case person.FieldDeathDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field death_date", values[i])
			} else if value.Valid {
				_m.DeathDate = value.Time
			}
		case person.FieldDeathPlace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field death_place", values[i])
			} else if value.Valid {
				_m.DeathPlace = value.String
			}
		case person.FieldDeathCause:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field death_cause", values[i])
			} else if value.Valid {
				_m.DeathCause = value.String
			}
		case person.FieldDeathDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field death_details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DeathDetails); err != nil {
					return fmt.Errorf("unmarshal field death_details: %w", err)
				}
			}
		case person.FieldBurialPlace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field burial_place", values[i])
			} else if value.Valid {
				_m.BurialPlace = value.String
			}
		case person.FieldBurialDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field burial_date", values[i])
			} else if value.Valid {
				_m.BurialDate = value.Time
			}
		case person.FieldOccupation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field occupation", values[i])
			} else if value.Valid {
				_m.Occupation = value.String
			}
		case person.FieldOccupationDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field occupation_details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OccupationDetails); err != nil {
					return fmt.Errorf("unmarshal field occupation_details: %w", err)
				}
			}
		case person.FieldEducation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field education", values[i])
			} else if value.Valid {
				_m.Education = value.String
			}
		case person.FieldReligion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field religion", values[i])
			} else if value.Valid {
				_m.Religion = value.String
			}
		case person.FieldNationality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nationality", values[i])
			} else if value.Valid {
				_m.Nationality = value.String
			}
		case person.FieldEthnicity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ethnicity", values[i])
			} else if value.Valid {
				_m.Ethnicity = value.String
			}
		case person.FieldAliases:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field aliases", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Aliases); err != nil {
					return fmt.Errorf("unmarshal field aliases: %w", err)
				}
			}
		case person.FieldNicknames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field nicknames", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Nicknames); err != nil {
					return fmt.Errorf("unmarshal field nicknames: %w", err)
				}
			}
		case person.FieldTitles:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field titles", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Titles); err != nil {
					return fmt.Errorf("unmarshal field titles: %w", err)
				}
			}
		case person.FieldHeight:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Height); err != nil {
					return fmt.Errorf("unmarshal field height: %w", err)
				}
			}
		case person.FieldWeight:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Weight); err != nil {
					return fmt.Errorf("unmarshal field weight: %w", err)
				}
			}
		case person.FieldBloodType:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field blood_type", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BloodType); err != nil {
					return fmt.Errorf("unmarshal field blood_type: %w", err)
				}
			}
		case person.FieldMedicalConditions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field medical_conditions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MedicalConditions); err != nil {
					return fmt.Errorf("unmarshal field medical_conditions: %w", err)
				}
			}
		case person.FieldGeneticMarkers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field genetic_markers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GeneticMarkers); err != nil {
					return fmt.Errorf("unmarshal field genetic_markers: %w", err)
				}
			}
		case person.FieldDnaMatches:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field dna_matches", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DnaMatches); err != nil {
					return fmt.Errorf("unmarshal field dna_matches: %w", err)
				}
			}
		case person.FieldPhotos:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field photos", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Photos); err != nil {
					return fmt.Errorf("unmarshal field photos: %w", err)
				}
			}
		case person.FieldDocuments:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field documents", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Documents); err != nil {
					return fmt.Errorf("unmarshal field documents: %w", err)
				}
			}
		case person.FieldEvents:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field events", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Events); err != nil {
					return fmt.Errorf("unmarshal field events: %w", err)
				}
			}
		case person.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case person.FieldSources:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field sources", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Sources); err != nil {
					return fmt.Errorf("unmarshal field sources: %w", err)
				}
			}
		case person.FieldSharedNotes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field shared_notes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SharedNotes); err != nil {
					return fmt.Errorf("unmarshal field shared_notes: %w", err)
				}
			}
		case person.FieldMedia:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field media", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Media); err != nil {
					return fmt.Errorf("unmarshal field media: %w", err)
				}
			}
		case person.FieldPrivacy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field privacy", values[i])
			} else if value.Valid {
				_m.Privacy = person.Privacy(value.String)
			}
		case person.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case person.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case person.FieldFatherID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field father_id", values[i])
			} else if value != nil {
				_m.FatherID = *value
			}
		case person.FieldMotherID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field mother_id", values[i])
			} else if value != nil {
				_m.MotherID = *value
			}
		case person.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				_m.CreatedBy = *value
			}
		case person.FieldUpdatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value != nil {
				_m.UpdatedBy = *value
			}
		case person.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field family_spouses", values[i])
			} else if value.Valid {
				_m.family_spouses = new(uuid.UUID)
				*_m.family_spouses = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Person.
// This includes values selected through modifiers, order, etc.
func (_m *Person) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Person entity.
func (_m *Person) QueryProject() *ProjectQuery {
	return NewPersonClient(_m.config).QueryProject(_m)
}

// QueryFather queries the "father" edge of the Person entity.
func (_m *Person) QueryFather() *PersonQuery {
	return NewPersonClient(_m.config).QueryFather(_m)
}

// QueryMother queries the "mother" edge of the Person entity.
func (_m *Person) QueryMother() *PersonQuery {
	return NewPersonClient(_m.config).QueryMother(_m)
}

// QueryChildren queries the "children" edge of the Person entity.
func (_m *Person) QueryChildren() *PersonQuery {
	return NewPersonClient(_m.config).QueryChildren(_m)
}

// QuerySpouses queries the "spouses" edge of the Person entity.
func (_m *Person) QuerySpouses() *PersonQuery {
	return NewPersonClient(_m.config).QuerySpouses(_m)
}

// QueryEntries queries the "entries" edge of the Person entity.
func (_m *Person) QueryEntries() *EntryQuery {
	return NewPersonClient(_m.config).QueryEntries(_m)
}

// QueryLinkedEntries queries the "linked_entries" edge of the Person entity.
func (_m *Person) QueryLinkedEntries() *EntryQuery {
	return NewPersonClient(_m.config).QueryLinkedEntries(_m)
}

// QueryRelatives queries the "relatives" edge of the Person entity.
func (_m *Person) QueryRelatives() *PersonQuery {
	return NewPersonClient(_m.config).QueryRelatives(_m)
}

// QueryAssociations queries the "associations" edge of the Person entity.
func (_m *Person) QueryAssociations() *PersonQuery {
	return NewPersonClient(_m.config).QueryAssociations(_m)
}

// QueryFamiliesAsHusband queries the "families_as_husband" edge of the Person entity.
func (_m *Person) QueryFamiliesAsHusband() *FamilyQuery {
	return NewPersonClient(_m.config).QueryFamiliesAsHusband(_m)
}

// QueryFamiliesAsWife queries the "families_as_wife" edge of the Person entity.
func (_m *Person) QueryFamiliesAsWife() *FamilyQuery {
	return NewPersonClient(_m.config).QueryFamiliesAsWife(_m)
}

// QueryFamiliesAsChild queries the "families_as_child" edge of the Person entity.
func (_m *Person) QueryFamiliesAsChild() *FamilyQuery {
	return NewPersonClient(_m.config).QueryFamiliesAsChild(_m)
}

// Update returns a builder for updating this Person.
// Note that you need to call Person.Unwrap() before calling this method if this Person
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Person) Update() *PersonUpdateOne {
	return NewPersonClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Person entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Person) Unwrap() *Person {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Person is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Person) String() string {
	var builder strings.Builder
	builder.WriteString("Person(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("external_id=")
	builder.WriteString(_m.ExternalID)
	builder.WriteString(", ")
	builder.WriteString("primary_name=")
	builder.WriteString(_m.PrimaryName)
	builder.WriteString(", ")
	builder.WriteString("names=")
	builder.WriteString(fmt.Sprintf("%v", _m.Names))
	builder.WriteString(", ")
	builder.WriteString("preferred_name=")
	builder.WriteString(_m.PreferredName)
	builder.WriteString(", ")
	builder.WriteString("maiden_name=")
	builder.WriteString(_m.MaidenName)
	builder.WriteString(", ")
	builder.WriteString("sex=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sex))
	builder.WriteString(", ")
	builder.WriteString("birth_date=")
	builder.WriteString(_m.BirthDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("birth_date_approx=")
	builder.WriteString(_m.BirthDateApprox)
	builder.WriteString(", ")
	builder.WriteString("birth_place=")
	builder.WriteString(_m.BirthPlace)
	builder.WriteString(", ")
	builder.WriteString("birth_place_jurisdiction=")
	builder.WriteString(fmt.Sprintf("%v", _m.BirthPlaceJurisdiction))
	builder.WriteString(", ")
	builder.WriteString("death_date=")
	builder.WriteString(_m.DeathDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("death_place=")
	builder.WriteString(_m.DeathPlace)
	builder.WriteString(", ")
	builder.WriteString("death_cause=")
	builder.WriteString(_m.DeathCause)
	builder.WriteString(", ")
	builder.WriteString("death_details=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeathDetails))
	builder.WriteString(", ")
	builder.WriteString("burial_place=")
	builder.WriteString(_m.BurialPlace)
	builder.WriteString(", ")
	builder.WriteString("burial_date=")
	builder.WriteString(_m.BurialDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("occupation=")
	builder.WriteString(_m.Occupation)
	builder.WriteString(", ")
	builder.WriteString("occupation_details=")
	builder.WriteString(fmt.Sprintf("%v", _m.OccupationDetails))
	builder.WriteString(", ")
	builder.WriteString("education=")
	builder.WriteString(_m.Education)
	builder.WriteString(", ")
	builder.WriteString("religion=")
	builder.WriteString(_m.Religion)
	builder.WriteString(", ")
	builder.WriteString("nationality=")
	builder.WriteString(_m.Nationality)
	builder.WriteString(", ")
	builder.WriteString("ethnicity=")
	builder.WriteString(_m.Ethnicity)
	builder.WriteString(", ")
	builder.WriteString("aliases=")
	builder.WriteString(fmt.Sprintf("%v", _m.Aliases))
	builder.WriteString(", ")
	builder.WriteString("nicknames=")
	builder.WriteString(fmt.Sprintf("%v", _m.Nicknames))
	builder.WriteString(", ")
	builder.WriteString("titles=")
	builder.WriteString(fmt.Sprintf("%v", _m.Titles))
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("blood_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.BloodType))
	builder.WriteString(", ")
	builder.WriteString("medical_conditions=")
	builder.WriteString(fmt.Sprintf("%v", _m.MedicalConditions))
	builder.WriteString(", ")
	builder.WriteString("genetic_markers=")
	builder.WriteString(fmt.Sprintf("%v", _m.GeneticMarkers))
	builder.WriteString(", ")
	builder.WriteString("dna_matches=")
	builder.WriteString(fmt.Sprintf("%v", _m.DnaMatches))
	builder.WriteString(", ")
	builder.WriteString("photos=")
	builder.WriteString(fmt.Sprintf("%v", _m.Photos))
	builder.WriteString(", ")
	builder.WriteString("documents=")
	builder.WriteString(fmt.Sprintf("%v", _m.Documents))
	builder.WriteString(", ")
	builder.WriteString("events=")
	builder.WriteString(fmt.Sprintf("%v", _m.Events))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("sources=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sources))
	builder.WriteString(", ")
	builder.WriteString("shared_notes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SharedNotes))
	builder.WriteString(", ")
	builder.WriteString("media=")
	builder.WriteString(fmt.Sprintf("%v", _m.Media))
	builder.WriteString(", ")
	builder.WriteString("privacy=")
	builder.WriteString(fmt.Sprintf("%v", _m.Privacy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("father_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FatherID))
	builder.WriteString(", ")
	builder.WriteString("mother_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MotherID))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteByte(')')
	return builder.String()
}

// Persons is a parsable slice of Person.
type Persons []*Person
