// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexlad/konservi/ent/entry"
	"github.com/plexlad/konservi/ent/family"
	"github.com/plexlad/konservi/ent/person"
	"github.com/plexlad/konservi/ent/project"
)

// PersonCreate is the builder for creating a Person entity.
type PersonCreate struct {
	config
	mutation *PersonMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *PersonCreate) SetProjectID(v uuid.UUID) *PersonCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *PersonCreate) SetExternalID(v string) *PersonCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *PersonCreate) SetNillableExternalID(v *string) *PersonCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetPrimaryName sets the "primary_name" field.
func (_c *PersonCreate) SetPrimaryName(v string) *PersonCreate {
	_c.mutation.SetPrimaryName(v)
	return _c
}

// SetNames sets the "names" field.
func (_c *PersonCreate) SetNames(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetNames(v)
	return _c
}

// SetPreferredName sets the "preferred_name" field.
func (_c *PersonCreate) SetPreferredName(v string) *PersonCreate {
	_c.mutation.SetPreferredName(v)
	return _c
}

// SetNillablePreferredName sets the "preferred_name" field if the given value is not nil.
func (_c *PersonCreate) SetNillablePreferredName(v *string) *PersonCreate {
	if v != nil {
		_c.SetPreferredName(*v)
	}
	return _c
}

// SetMaidenName sets the "maiden_name" field.
func (_c *PersonCreate) SetMaidenName(v string) *PersonCreate {
	_c.mutation.SetMaidenName(v)
	return _c
}

// SetNillableMaidenName sets the "maiden_name" field if the given value is not nil.
func (_c *PersonCreate) SetNillableMaidenName(v *string) *PersonCreate {
	if v != nil {
		_c.SetMaidenName(*v)
	}
	return _c
}

// SetSex sets the "sex" field.
func (_c *PersonCreate) SetSex(v person.Sex) *PersonCreate {
	_c.mutation.SetSex(v)
	return _c
}

// SetBirthDate sets the "birth_date" field.
func (_c *PersonCreate) SetBirthDate(v time.Time) *PersonCreate {
	_c.mutation.SetBirthDate(v)
	return _c
}

// SetNillableBirthDate sets the "birth_date" field if the given value is not nil.
func (_c *PersonCreate) SetNillableBirthDate(v *time.Time) *PersonCreate {
	if v != nil {
		_c.SetBirthDate(*v)
	}
	return _c
}

// SetBirthDateApprox sets the "birth_date_approx" field.
func (_c *PersonCreate) SetBirthDateApprox(v string) *PersonCreate {
	_c.mutation.SetBirthDateApprox(v)
	return _c
}

// SetNillableBirthDateApprox sets the "birth_date_approx" field if the given value is not nil.
func (_c *PersonCreate) SetNillableBirthDateApprox(v *string) *PersonCreate {
	if v != nil {
		_c.SetBirthDateApprox(*v)
	}
	return _c
}

// SetBirthPlace sets the "birth_place" field.
func (_c *PersonCreate) SetBirthPlace(v string) *PersonCreate {
	_c.mutation.SetBirthPlace(v)
	return _c
}

// SetNillableBirthPlace sets the "birth_place" field if the given value is not nil.
func (_c *PersonCreate) SetNillableBirthPlace(v *string) *PersonCreate {
	if v != nil {
		_c.SetBirthPlace(*v)
	}
	return _c
}

// SetBirthPlaceJurisdiction sets the "birth_place_jurisdiction" field.
func (_c *PersonCreate) SetBirthPlaceJurisdiction(v []string) *PersonCreate {
	_c.mutation.SetBirthPlaceJurisdiction(v)
	return _c
}

// SetDeathDate sets the "death_date" field.
func (_c *PersonCreate) SetDeathDate(v time.Time) *PersonCreate {
	_c.mutation.SetDeathDate(v)
	return _c
}

// SetNillableDeathDate sets the "death_date" field if the given value is not nil.
func (_c *PersonCreate) SetNillableDeathDate(v *time.Time) *PersonCreate {
	if v != nil {
		_c.SetDeathDate(*v)
	}
	return _c
}

// SetDeathPlace sets the "death_place" field.
func (_c *PersonCreate) SetDeathPlace(v string) *PersonCreate {
	_c.mutation.SetDeathPlace(v)
	return _c
}

// SetNillableDeathPlace sets the "death_place" field if the given value is not nil.
func (_c *PersonCreate) SetNillableDeathPlace(v *string) *PersonCreate {
	if v != nil {
		_c.SetDeathPlace(*v)
	}
	return _c
}

// SetDeathCause sets the "death_cause" field.
func (_c *PersonCreate) SetDeathCause(v string) *PersonCreate {
	_c.mutation.SetDeathCause(v)
	return _c
}

// SetNillableDeathCause sets the "death_cause" field if the given value is not nil.
func (_c *PersonCreate) SetNillableDeathCause(v *string) *PersonCreate {
	if v != nil {
		_c.SetDeathCause(*v)
	}
	return _c
}

// SetDeathDetails sets the "death_details" field.
func (_c *PersonCreate) SetDeathDetails(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetDeathDetails(v)
	return _c
}

// SetBurialPlace sets the "burial_place" field.
func (_c *PersonCreate) SetBurialPlace(v string) *PersonCreate {
	_c.mutation.SetBurialPlace(v)
	return _c
}

// SetNillableBurialPlace sets the "burial_place" field if the given value is not nil.
func (_c *PersonCreate) SetNillableBurialPlace(v *string) *PersonCreate {
	if v != nil {
		_c.SetBurialPlace(*v)
	}
	return _c
}

// SetBurialDate sets the "burial_date" field.
func (_c *PersonCreate) SetBurialDate(v time.Time) *PersonCreate {
	_c.mutation.SetBurialDate(v)
	return _c
}

// SetNillableBurialDate sets the "burial_date" field if the given value is not nil.
func (_c *PersonCreate) SetNillableBurialDate(v *time.Time) *PersonCreate {
	if v != nil {
		_c.SetBurialDate(*v)
	}
	return _c
}

// SetOccupation sets the "occupation" field.
func (_c *PersonCreate) SetOccupation(v string) *PersonCreate {
	_c.mutation.SetOccupation(v)
	return _c
}

// SetNillableOccupation sets the "occupation" field if the given value is not nil.
func (_c *PersonCreate) SetNillableOccupation(v *string) *PersonCreate {
	if v != nil {
		_c.SetOccupation(*v)
	}
	return _c
}

// SetOccupationDetails sets the "occupation_details" field.
func (_c *PersonCreate) SetOccupationDetails(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetOccupationDetails(v)
	return _c
}

// SetEducation sets the "education" field.
func (_c *PersonCreate) SetEducation(v string) *PersonCreate {
	_c.mutation.SetEducation(v)
	return _c
}

// SetNillableEducation sets the "education" field if the given value is not nil.
func (_c *PersonCreate) SetNillableEducation(v *string) *PersonCreate {
	if v != nil {
		_c.SetEducation(*v)
	}
	return _c
}

// SetReligion sets the "religion" field.
func (_c *PersonCreate) SetReligion(v string) *PersonCreate {
	_c.mutation.SetReligion(v)
	return _c
}

// SetNillableReligion sets the "religion" field if the given value is not nil.
func (_c *PersonCreate) SetNillableReligion(v *string) *PersonCreate {
	if v != nil {
		_c.SetReligion(*v)
	}
	return _c
}

// SetNationality sets the "nationality" field.
func (_c *PersonCreate) SetNationality(v string) *PersonCreate {
	_c.mutation.SetNationality(v)
	return _c
}

// SetNillableNationality sets the "nationality" field if the given value is not nil.
func (_c *PersonCreate) SetNillableNationality(v *string) *PersonCreate {
	if v != nil {
		_c.SetNationality(*v)
	}
	return _c
}

// SetEthnicity sets the "ethnicity" field.
func (_c *PersonCreate) SetEthnicity(v string) *PersonCreate {
	_c.mutation.SetEthnicity(v)
	return _c
}

// SetNillableEthnicity sets the "ethnicity" field if the given value is not nil.
func (_c *PersonCreate) SetNillableEthnicity(v *string) *PersonCreate {
	if v != nil {
		_c.SetEthnicity(*v)
	}
	return _c
}

// SetAliases sets the "aliases" field.
func (_c *PersonCreate) SetAliases(v []string) *PersonCreate {
	_c.mutation.SetAliases(v)
	return _c
}

// SetNicknames sets the "nicknames" field.
func (_c *PersonCreate) SetNicknames(v []string) *PersonCreate {
	_c.mutation.SetNicknames(v)
	return _c
}

// SetTitles sets the "titles" field.
func (_c *PersonCreate) SetTitles(v []string) *PersonCreate {
	_c.mutation.SetTitles(v)
	return _c
}

// SetHeight sets the "height" field.
func (_c *PersonCreate) SetHeight(v map[string]interface{}) *PersonCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetWeight sets the "weight" field.
func (_c *PersonCreate) SetWeight(v map[string]interface{}) *PersonCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetBloodType sets the "blood_type" field.
func (_c *PersonCreate) SetBloodType(v map[string]interface{}) *PersonCreate {
	_c.mutation.SetBloodType(v)
	return _c
}

// SetMedicalConditions sets the "medical_conditions" field.
func (_c *PersonCreate) SetMedicalConditions(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetMedicalConditions(v)
	return _c
}

// SetGeneticMarkers sets the "genetic_markers" field.
func (_c *PersonCreate) SetGeneticMarkers(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetGeneticMarkers(v)
	return _c
}

// SetDnaMatches sets the "dna_matches" field.
func (_c *PersonCreate) SetDnaMatches(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetDnaMatches(v)
	return _c
}

// SetPhotos sets the "photos" field.
func (_c *PersonCreate) SetPhotos(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetPhotos(v)
	return _c
}

// SetDocuments sets the "documents" field.
func (_c *PersonCreate) SetDocuments(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetDocuments(v)
	return _c
}

// SetEvents sets the "events" field.
func (_c *PersonCreate) SetEvents(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetEvents(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *PersonCreate) SetNotes(v string) *PersonCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *PersonCreate) SetNillableNotes(v *string) *PersonCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetSources sets the "sources" field.
func (_c *PersonCreate) SetSources(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetSources(v)
	return _c
}

// SetSharedNotes sets the "shared_notes" field.
func (_c *PersonCreate) SetSharedNotes(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetSharedNotes(v)
	return _c
}

// SetMedia sets the "media" field.
func (_c *PersonCreate) SetMedia(v []map[string]interface{}) *PersonCreate {
	_c.mutation.SetMedia(v)
	return _c
}

// SetPrivacy sets the "privacy" field.
func (_c *PersonCreate) SetPrivacy(v person.Privacy) *PersonCreate {
	_c.mutation.SetPrivacy(v)
	return _c
}

// SetNillablePrivacy sets the "privacy" field if the given value is not nil.
func (_c *PersonCreate) SetNillablePrivacy(v *person.Privacy) *PersonCreate {
	if v != nil {
		_c.SetPrivacy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PersonCreate) SetCreatedAt(v time.Time) *PersonCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PersonCreate) SetNillableCreatedAt(v *time.Time) *PersonCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PersonCreate) SetUpdatedAt(v time.Time) *PersonCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PersonCreate) SetNillableUpdatedAt(v *time.Time) *PersonCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetFatherID sets the "father_id" field.
func (_c *PersonCreate) SetFatherID(v uuid.UUID) *PersonCreate {
	_c.mutation.SetFatherID(v)
	return _c
}

// SetNillableFatherID sets the "father_id" field if the given value is not nil.
func (_c *PersonCreate) SetNillableFatherID(v *uuid.UUID) *PersonCreate {
	if v != nil {
		_c.SetFatherID(*v)
	}
	return _c
}

// SetMotherID sets the "mother_id" field.
func (_c *PersonCreate) SetMotherID(v uuid.UUID) *PersonCreate {
	_c.mutation.SetMotherID(v)
	return _c
}

// SetNillableMotherID sets the "mother_id" field if the given value is not nil.
func (_c *PersonCreate) SetNillableMotherID(v *uuid.UUID) *PersonCreate {
	if v != nil {
		_c.SetMotherID(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PersonCreate) SetCreatedBy(v uuid.UUID) *PersonCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *PersonCreate) SetNillableCreatedBy(v *uuid.UUID) *PersonCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *PersonCreate) SetUpdatedBy(v uuid.UUID) *PersonCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *PersonCreate) SetNillableUpdatedBy(v *uuid.UUID) *PersonCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PersonCreate) SetID(v uuid.UUID) *PersonCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PersonCreate) SetNillableID(v *uuid.UUID) *PersonCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *PersonCreate) SetProject(v *Project) *PersonCreate {
	return _c.SetProjectID(v.ID)
}

// SetFather sets the "father" edge to the Person entity.
func (_c *PersonCreate) SetFather(v *Person) *PersonCreate {
	return _c.SetFatherID(v.ID)
}

// SetMother sets the "mother" edge to the Person entity.
func (_c *PersonCreate) SetMother(v *Person) *PersonCreate {
	return _c.SetMotherID(v.ID)
}

// AddChildIDs adds the "children" edge to the Person entity by IDs.
func (_c *PersonCreate) AddChildIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Person entity.
func (_c *PersonCreate) AddChildren(v ...*Person) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddSpouseIDs adds the "spouses" edge to the Person entity by IDs.
func (_c *PersonCreate) AddSpouseIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddSpouseIDs(ids...)
	return _c
}

// AddSpouses adds the "spouses" edges to the Person entity.
func (_c *PersonCreate) AddSpouses(v ...*Person) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSpouseIDs(ids...)
}

// AddEntryIDs adds the "entries" edge to the Entry entity by IDs.
func (_c *PersonCreate) AddEntryIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddEntryIDs(ids...)
	return _c
}

// AddEntries adds the "entries" edges to the Entry entity.
func (_c *PersonCreate) AddEntries(v ...*Entry) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEntryIDs(ids...)
}

// AddLinkedEntryIDs adds the "linked_entries" edge to the Entry entity by IDs.
func (_c *PersonCreate) AddLinkedEntryIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddLinkedEntryIDs(ids...)
	return _c
}

// AddLinkedEntries adds the "linked_entries" edges to the Entry entity.
func (_c *PersonCreate) AddLinkedEntries(v ...*Entry) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLinkedEntryIDs(ids...)
}

// AddRelativeIDs adds the "relatives" edge to the Person entity by IDs.
func (_c *PersonCreate) AddRelativeIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddRelativeIDs(ids...)
	return _c
}

// AddRelatives adds the "relatives" edges to the Person entity.
func (_c *PersonCreate) AddRelatives(v ...*Person) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRelativeIDs(ids...)
}

// AddAssociationIDs adds the "associations" edge to the Person entity by IDs.
func (_c *PersonCreate) AddAssociationIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddAssociationIDs(ids...)
	return _c
}

// AddAssociations adds the "associations" edges to the Person entity.
func (_c *PersonCreate) AddAssociations(v ...*Person) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssociationIDs(ids...)
}

// AddFamiliesAsHusbandIDs adds the "families_as_husband" edge to the Family entity by IDs.
func (_c *PersonCreate) AddFamiliesAsHusbandIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddFamiliesAsHusbandIDs(ids...)
	return _c
}

// AddFamiliesAsHusband adds the "families_as_husband" edges to the Family entity.
func (_c *PersonCreate) AddFamiliesAsHusband(v ...*Family) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFamiliesAsHusbandIDs(ids...)
}

// AddFamiliesAsWifeIDs adds the "families_as_wife" edge to the Family entity by IDs.
func (_c *PersonCreate) AddFamiliesAsWifeIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddFamiliesAsWifeIDs(ids...)
	return _c
}

// AddFamiliesAsWife adds the "families_as_wife" edges to the Family entity.
func (_c *PersonCreate) AddFamiliesAsWife(v ...*Family) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFamiliesAsWifeIDs(ids...)
}

// AddFamiliesAsChildIDs adds the "families_as_child" edge to the Family entity by IDs.
func (_c *PersonCreate) AddFamiliesAsChildIDs(ids ...uuid.UUID) *PersonCreate {
	_c.mutation.AddFamiliesAsChildIDs(ids...)
	return _c
}

// AddFamiliesAsChild adds the "families_as_child" edges to the Family entity.
func (_c *PersonCreate) AddFamiliesAsChild(v ...*Family) *PersonCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFamiliesAsChildIDs(ids...)
}

// Mutation returns the PersonMutation object of the builder.
func (_c *PersonCreate) Mutation() *PersonMutation {
	return _c.mutation
}

// Save creates the Person in the database.
func (_c *PersonCreate) Save(ctx context.Context) (*Person, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PersonCreate) SaveX(ctx context.Context) *Person {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PersonCreate) defaults() {
	if _, ok := _c.mutation.Privacy(); !ok {
		v := person.DefaultPrivacy
		_c.mutation.SetPrivacy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := person.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := person.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := person.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PersonCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Person.project_id"`)}
	}
	if _, ok := _c.mutation.PrimaryName(); !ok {
		return &ValidationError{Name: "primary_name", err: errors.New(`ent: missing required field "Person.primary_name"`)}
	}
	if v, ok := _c.mutation.PrimaryName(); ok {
		if err := person.PrimaryNameValidator(v); err != nil {
			return &ValidationError{Name: "primary_name", err: fmt.Errorf(`ent: validator failed for field "Person.primary_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sex(); !ok {
		return &ValidationError{Name: "sex", err: errors.New(`ent: missing required field "Person.sex"`)}
	}
	if v, ok := _c.mutation.Sex(); ok {
		if err := person.SexValidator(v); err != nil {
			return &ValidationError{Name: "sex", err: fmt.Errorf(`ent: validator failed for field "Person.sex": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Privacy(); !ok {
		return &ValidationError{Name: "privacy", err: errors.New(`ent: missing required field "Person.privacy"`)}
	}
	if v, ok := _c.mutation.Privacy(); ok {
		if err := person.PrivacyValidator(v); err != nil {
			return &ValidationError{Name: "privacy", err: fmt.Errorf(`ent: validator failed for field "Person.privacy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Person.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Person.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Person.project"`)}
	}
	return nil
}

func (_c *PersonCreate) sqlSave(ctx context.Context) (*Person, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PersonCreate) createSpec() (*Person, *sqlgraph.CreateSpec) {
	var (
		_node = &Person{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(person.Table, sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(person.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.PrimaryName(); ok {
		_spec.SetField(person.FieldPrimaryName, field.TypeString, value)
		_node.PrimaryName = value
	}
	if value, ok := _c.mutation.Names(); ok {
		_spec.SetField(person.FieldNames, field.TypeJSON, value)
		_node.Names = value
	}
	if value, ok := _c.mutation.PreferredName(); ok {
		_spec.SetField(person.FieldPreferredName, field.TypeString, value)
		_node.PreferredName = value
	}
	if value, ok := _c.mutation.MaidenName(); ok {
		_spec.SetField(person.FieldMaidenName, field.TypeString, value)
		_node.MaidenName = value
	}
	if value, ok := _c.mutation.Sex(); ok {
		_spec.SetField(person.FieldSex, field.TypeEnum, value)
		_node.Sex = value
	}
	if value, ok := _c.mutation.BirthDate(); ok {
		_spec.SetField(person.FieldBirthDate, field.TypeTime, value)
		_node.BirthDate = value
	}
	if value, ok := _c.mutation.BirthDateApprox(); ok {
		_spec.SetField(person.FieldBirthDateApprox, field.TypeString, value)
		_node.BirthDateApprox = value
	}
	if value, ok := _c.mutation.BirthPlace(); ok {
		_spec.SetField(person.FieldBirthPlace, field.TypeString, value)
		_node.BirthPlace = value
	}
	if value, ok := _c.mutation.BirthPlaceJurisdiction(); ok {
		_spec.SetField(person.FieldBirthPlaceJurisdiction, field.TypeJSON, value)
		_node.BirthPlaceJurisdiction = value
	}
	if value, ok := _c.mutation.DeathDate(); ok {
		_spec.SetField(person.FieldDeathDate, field.TypeTime, value)
		_node.DeathDate = value
	}
	if value, ok := _c.mutation.DeathPlace(); ok {
		_spec.SetField(person.FieldDeathPlace, field.TypeString, value)
		_node.DeathPlace = value
	}
	if value, ok := _c.mutation.DeathCause(); ok {
		_spec.SetField(person.FieldDeathCause, field.TypeString, value)
		_node.DeathCause = value
	}
	if value, ok := _c.mutation.DeathDetails(); ok {
		_spec.SetField(person.FieldDeathDetails, field.TypeJSON, value)
		_node.DeathDetails = value
	}
	if value, ok := _c.mutation.BurialPlace(); ok {
		_spec.SetField(person.FieldBurialPlace, field.TypeString, value)
		_node.BurialPlace = value
	}
	if value, ok := _c.mutation.BurialDate(); ok {
		_spec.SetField(person.FieldBurialDate, field.TypeTime, value)
		_node.BurialDate = value
	}
	if value, ok := _c.mutation.Occupation(); ok {
		_spec.SetField(person.FieldOccupation, field.TypeString, value)
		_node.Occupation = value
	}
	if value, ok := _c.mutation.OccupationDetails(); ok {
		_spec.SetField(person.FieldOccupationDetails, field.TypeJSON, value)
		_node.OccupationDetails = value
	}
	if value, ok := _c.mutation.Education(); ok {
		_spec.SetField(person.FieldEducation, field.TypeString, value)
		_node.Education = value
	}
	if value, ok := _c.mutation.Religion(); ok {
		_spec.SetField(person.FieldReligion, field.TypeString, value)
		_node.Religion = value
	}
	if value, ok := _c.mutation.Nationality(); ok {
		_spec.SetField(person.FieldNationality, field.TypeString, value)
		_node.Nationality = value
	}
	if value, ok := _c.mutation.Ethnicity(); ok {
		_spec.SetField(person.FieldEthnicity, field.TypeString, value)
		_node.Ethnicity = value
	}
	if value, ok := _c.mutation.Aliases(); ok {
		_spec.SetField(person.FieldAliases, field.TypeJSON, value)
		_node.Aliases = value
	}
	if value, ok := _c.mutation.Nicknames(); ok {
		_spec.SetField(person.FieldNicknames, field.TypeJSON, value)
		_node.Nicknames = value
	}
	if value, ok := _c.mutation.Titles(); ok {
		_spec.SetField(person.FieldTitles, field.TypeJSON, value)
		_node.Titles = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(person.FieldHeight, field.TypeJSON, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(person.FieldWeight, field.TypeJSON, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.BloodType(); ok {
		_spec.SetField(person.FieldBloodType, field.TypeJSON, value)
		_node.BloodType = value
	}
	if value, ok := _c.mutation.MedicalConditions(); ok {
		_spec.SetField(person.FieldMedicalConditions, field.TypeJSON, value)
		_node.MedicalConditions = value
	}
	if value, ok := _c.mutation.GeneticMarkers(); ok {
		_spec.SetField(person.FieldGeneticMarkers, field.TypeJSON, value)
		_node.GeneticMarkers = value
	}
	if value, ok := _c.mutation.DnaMatches(); ok {
		_spec.SetField(person.FieldDnaMatches, field.TypeJSON, value)
		_node.DnaMatches = value
	}
	if value, ok := _c.mutation.Photos(); ok {
		_spec.SetField(person.FieldPhotos, field.TypeJSON, value)
		_node.Photos = value
	}
	if value, ok := _c.mutation.Documents(); ok {
		_spec.SetField(person.FieldDocuments, field.TypeJSON, value)
		_node.Documents = value
	}
	if value, ok := _c.mutation.Events(); ok {
		_spec.SetField(person.FieldEvents, field.TypeJSON, value)
		_node.Events = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(person.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.Sources(); ok {
		_spec.SetField(person.FieldSources, field.TypeJSON, value)
		_node.Sources = value
	}
	if value, ok := _c.mutation.SharedNotes(); ok {
		_spec.SetField(person.FieldSharedNotes, field.TypeJSON, value)
		_node.SharedNotes = value
	}
	if value, ok := _c.mutation.Media(); ok {
		_spec.SetField(person.FieldMedia, field.TypeJSON, value)
		_node.Media = value
	}
	if value, ok := _c.mutation.Privacy(); ok {
		_spec.SetField(person.FieldPrivacy, field.TypeEnum, value)
		_node.Privacy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(person.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(person.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(person.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(person.FieldUpdatedBy, field.TypeUUID, value)
		_node.UpdatedBy = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   person.ProjectTable,
			Columns: []string{person.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FatherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   person.FatherTable,
			Columns: []string{person.FatherColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FatherID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MotherIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   person.MotherTable,
			Columns: []string{person.MotherColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MotherID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.ChildrenTable,
			Columns: person.ChildrenPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SpousesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.SpousesTable,
			Columns: person.SpousesPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   person.EntriesTable,
			Columns: []string{person.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LinkedEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   person.LinkedEntriesTable,
			Columns: person.LinkedEntriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RelativesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.RelativesTable,
			Columns: person.RelativesPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssociationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   person.AssociationsTable,
			Columns: person.AssociationsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FamiliesAsHusbandIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   person.FamiliesAsHusbandTable,
			Columns: []string{person.FamiliesAsHusbandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FamiliesAsWifeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   person.FamiliesAsWifeTable,
			Columns: []string{person.FamiliesAsWifeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FamiliesAsChildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   person.FamiliesAsChildTable,
			Columns: person.FamiliesAsChildPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PersonCreateBulk is the builder for creating many Person entities in bulk.
type PersonCreateBulk struct {
	config
	err      error
	builders []*PersonCreate
}

// Save creates the Person entities in the database.
func (_c *PersonCreateBulk) Save(ctx context.Context) ([]*Person, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Person, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PersonMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PersonCreateBulk) SaveX(ctx context.Context) []*Person {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
