// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexlad/konservi/ent/entry"
	"github.com/plexlad/konservi/ent/family"
	"github.com/plexlad/konservi/ent/person"
	"github.com/plexlad/konservi/ent/predicate"
	"github.com/plexlad/konservi/ent/project"
	"github.com/plexlad/konservi/ent/projectmembership"
	"github.com/plexlad/konservi/ent/user"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectUpdate) SetName(v string) *ProjectUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableName(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdate) SetDescription(v string) *ProjectUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableDescription(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectUpdate) ClearDescription() *ProjectUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *ProjectUpdate) SetOwnerID(v uuid.UUID) *ProjectUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableOwnerID(v *uuid.UUID) *ProjectUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ProjectUpdate) SetOwner(v *User) *ProjectUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the ProjectMembership entity by IDs.
func (_u *ProjectUpdate) AddMembershipIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the ProjectMembership entity.
func (_u *ProjectUpdate) AddMemberships(v ...*ProjectMembership) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddEntryIDs adds the "entries" edge to the Entry entity by IDs.
func (_u *ProjectUpdate) AddEntryIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the Entry entity.
func (_u *ProjectUpdate) AddEntries(v ...*Entry) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// AddPersonIDs adds the "people" edge to the Person entity by IDs.
func (_u *ProjectUpdate) AddPersonIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddPersonIDs(ids...)
	return _u
}

// AddPeople adds the "people" edges to the Person entity.
func (_u *ProjectUpdate) AddPeople(v ...*Person) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPersonIDs(ids...)
}

// AddFamilyIDs adds the "families" edge to the Family entity by IDs.
func (_u *ProjectUpdate) AddFamilyIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddFamilyIDs(ids...)
	return _u
}

// AddFamilies adds the "families" edges to the Family entity.
func (_u *ProjectUpdate) AddFamilies(v ...*Family) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFamilyIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ProjectUpdate) ClearOwner() *ProjectUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMemberships clears all "memberships" edges to the ProjectMembership entity.
func (_u *ProjectUpdate) ClearMemberships() *ProjectUpdate {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to ProjectMembership entities by IDs.
func (_u *ProjectUpdate) RemoveMembershipIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to ProjectMembership entities.
func (_u *ProjectUpdate) RemoveMemberships(v ...*ProjectMembership) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearEntries clears all "entries" edges to the Entry entity.
func (_u *ProjectUpdate) ClearEntries() *ProjectUpdate {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to Entry entities by IDs.
func (_u *ProjectUpdate) RemoveEntryIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to Entry entities.
func (_u *ProjectUpdate) RemoveEntries(v ...*Entry) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// ClearPeople clears all "people" edges to the Person entity.
func (_u *ProjectUpdate) ClearPeople() *ProjectUpdate {
	_u.mutation.ClearPeople()
	return _u
}

// RemovePersonIDs removes the "people" edge to Person entities by IDs.
func (_u *ProjectUpdate) RemovePersonIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemovePersonIDs(ids...)
	return _u
}

// RemovePeople removes "people" edges to Person entities.
func (_u *ProjectUpdate) RemovePeople(v ...*Person) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePersonIDs(ids...)
}

// ClearFamilies clears all "families" edges to the Family entity.
func (_u *ProjectUpdate) ClearFamilies() *ProjectUpdate {
	_u.mutation.ClearFamilies()
	return _u
}

// RemoveFamilyIDs removes the "families" edge to Family entities by IDs.
func (_u *ProjectUpdate) RemoveFamilyIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveFamilyIDs(ids...)
	return _u
}

// RemoveFamilies removes "families" edges to Family entities.
func (_u *ProjectUpdate) RemoveFamilies(v ...*Family) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFamilyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Project.owner"`)
	}
	return nil
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OwnerTable,
			Columns: []string{project.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OwnerTable,
			Columns: []string{project.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.MembershipsTable,
			Columns: []string{project.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmembership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.MembershipsTable,
			Columns: []string{project.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.MembershipsTable,
			Columns: []string{project.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.EntriesTable,
			Columns: []string{project.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.EntriesTable,
			Columns: []string{project.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.EntriesTable,
			Columns: []string{project.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PeopleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.PeopleTable,
			Columns: []string{project.PeopleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPeopleIDs(); len(nodes) > 0 && !_u.mutation.PeopleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.PeopleTable,
			Columns: []string{project.PeopleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PeopleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.PeopleTable,
			Columns: []string{project.PeopleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FamiliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.FamiliesTable,
			Columns: []string{project.FamiliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFamiliesIDs(); len(nodes) > 0 && !_u.mutation.FamiliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.FamiliesTable,
			Columns: []string{project.FamiliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FamiliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.FamiliesTable,
			Columns: []string{project.FamiliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetName sets the "name" field.
func (_u *ProjectUpdateOne) SetName(v string) *ProjectUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableName(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdateOne) SetDescription(v string) *ProjectUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableDescription(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectUpdateOne) ClearDescription() *ProjectUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *ProjectUpdateOne) SetOwnerID(v uuid.UUID) *ProjectUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableOwnerID(v *uuid.UUID) *ProjectUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ProjectUpdateOne) SetOwner(v *User) *ProjectUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the ProjectMembership entity by IDs.
func (_u *ProjectUpdateOne) AddMembershipIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the ProjectMembership entity.
func (_u *ProjectUpdateOne) AddMemberships(v ...*ProjectMembership) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddEntryIDs adds the "entries" edge to the Entry entity by IDs.
func (_u *ProjectUpdateOne) AddEntryIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the Entry entity.
func (_u *ProjectUpdateOne) AddEntries(v ...*Entry) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// AddPersonIDs adds the "people" edge to the Person entity by IDs.
func (_u *ProjectUpdateOne) AddPersonIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddPersonIDs(ids...)
	return _u
}

// AddPeople adds the "people" edges to the Person entity.
func (_u *ProjectUpdateOne) AddPeople(v ...*Person) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPersonIDs(ids...)
}

// AddFamilyIDs adds the "families" edge to the Family entity by IDs.
func (_u *ProjectUpdateOne) AddFamilyIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddFamilyIDs(ids...)
	return _u
}

// AddFamilies adds the "families" edges to the Family entity.
func (_u *ProjectUpdateOne) AddFamilies(v ...*Family) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFamilyIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ProjectUpdateOne) ClearOwner() *ProjectUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMemberships clears all "memberships" edges to the ProjectMembership entity.
func (_u *ProjectUpdateOne) ClearMemberships() *ProjectUpdateOne {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to ProjectMembership entities by IDs.
func (_u *ProjectUpdateOne) RemoveMembershipIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to ProjectMembership entities.
func (_u *ProjectUpdateOne) RemoveMemberships(v ...*ProjectMembership) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearEntries clears all "entries" edges to the Entry entity.
func (_u *ProjectUpdateOne) ClearEntries() *ProjectUpdateOne {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to Entry entities by IDs.
func (_u *ProjectUpdateOne) RemoveEntryIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to Entry entities.
func (_u *ProjectUpdateOne) RemoveEntries(v ...*Entry) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// ClearPeople clears all "people" edges to the Person entity.
func (_u *ProjectUpdateOne) ClearPeople() *ProjectUpdateOne {
	_u.mutation.ClearPeople()
	return _u
}

// RemovePersonIDs removes the "people" edge to Person entities by IDs.
func (_u *ProjectUpdateOne) RemovePersonIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemovePersonIDs(ids...)
	return _u
}

// RemovePeople removes "people" edges to Person entities.
func (_u *ProjectUpdateOne) RemovePeople(v ...*Person) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePersonIDs(ids...)
}

// ClearFamilies clears all "families" edges to the Family entity.
func (_u *ProjectUpdateOne) ClearFamilies() *ProjectUpdateOne {
	_u.mutation.ClearFamilies()
	return _u
}

// RemoveFamilyIDs removes the "families" edge to Family entities by IDs.
func (_u *ProjectUpdateOne) RemoveFamilyIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveFamilyIDs(ids...)
	return _u
}

// RemoveFamilies removes "families" edges to Family entities.
func (_u *ProjectUpdateOne) RemoveFamilies(v ...*Family) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFamilyIDs(ids...)
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Project.owner"`)
	}
	return nil
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OwnerTable,
			Columns: []string{project.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OwnerTable,
			Columns: []string{project.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.MembershipsTable,
			Columns: []string{project.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmembership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.MembershipsTable,
			Columns: []string{project.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.MembershipsTable,
			Columns: []string{project.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmembership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.EntriesTable,
			Columns: []string{project.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.EntriesTable,
			Columns: []string{project.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.EntriesTable,
			Columns: []string{project.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PeopleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.PeopleTable,
			Columns: []string{project.PeopleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPeopleIDs(); len(nodes) > 0 && !_u.mutation.PeopleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.PeopleTable,
			Columns: []string{project.PeopleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PeopleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.PeopleTable,
			Columns: []string{project.PeopleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FamiliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.FamiliesTable,
			Columns: []string{project.FamiliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFamiliesIDs(); len(nodes) > 0 && !_u.mutation.FamiliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.FamiliesTable,
			Columns: []string{project.FamiliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FamiliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.FamiliesTable,
			Columns: []string{project.FamiliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(family.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
