// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/plexlad/konservi/ent/predicate"
	"github.com/plexlad/konservi/ent/project"
	"github.com/plexlad/konservi/ent/projectmembership"
	"github.com/plexlad/konservi/ent/user"
)

// ProjectMembershipUpdate is the builder for updating ProjectMembership entities.
type ProjectMembershipUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMembershipMutation
}

// Where appends a list predicates to the ProjectMembershipUpdate builder.
func (_u *ProjectMembershipUpdate) Where(ps ...predicate.ProjectMembership) *ProjectMembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ProjectMembershipUpdate) SetUserID(v uuid.UUID) *ProjectMembershipUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProjectMembershipUpdate) SetNillableUserID(v *uuid.UUID) *ProjectMembershipUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectMembershipUpdate) SetProjectID(v uuid.UUID) *ProjectMembershipUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectMembershipUpdate) SetNillableProjectID(v *uuid.UUID) *ProjectMembershipUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ProjectMembershipUpdate) SetRole(v projectmembership.Role) *ProjectMembershipUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ProjectMembershipUpdate) SetNillableRole(v *projectmembership.Role) *ProjectMembershipUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProjectMembershipUpdate) SetUser(v *User) *ProjectMembershipUpdate {
	return _u.SetUserID(v.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectMembershipUpdate) SetProject(v *Project) *ProjectMembershipUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectMembershipMutation object of the builder.
func (_u *ProjectMembershipUpdate) Mutation() *ProjectMembershipMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProjectMembershipUpdate) ClearUser() *ProjectMembershipUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectMembershipUpdate) ClearProject() *ProjectMembershipUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectMembershipUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectMembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectMembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectMembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectMembershipUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := projectmembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ProjectMembership.role": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectMembership.user"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectMembership.project"`)
	}
	return nil
}

func (_u *ProjectMembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectmembership.Table, projectmembership.Columns, sqlgraph.NewFieldSpec(projectmembership.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(projectmembership.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmembership.UserTable,
			Columns: []string{projectmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmembership.UserTable,
			Columns: []string{projectmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmembership.ProjectTable,
			Columns: []string{projectmembership.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmembership.ProjectTable,
			Columns: []string{projectmembership.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectMembershipUpdateOne is the builder for updating a single ProjectMembership entity.
type ProjectMembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMembershipMutation
}

// SetUserID sets the "user_id" field.
func (_u *ProjectMembershipUpdateOne) SetUserID(v uuid.UUID) *ProjectMembershipUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProjectMembershipUpdateOne) SetNillableUserID(v *uuid.UUID) *ProjectMembershipUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectMembershipUpdateOne) SetProjectID(v uuid.UUID) *ProjectMembershipUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectMembershipUpdateOne) SetNillableProjectID(v *uuid.UUID) *ProjectMembershipUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ProjectMembershipUpdateOne) SetRole(v projectmembership.Role) *ProjectMembershipUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ProjectMembershipUpdateOne) SetNillableRole(v *projectmembership.Role) *ProjectMembershipUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ProjectMembershipUpdateOne) SetUser(v *User) *ProjectMembershipUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectMembershipUpdateOne) SetProject(v *Project) *ProjectMembershipUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectMembershipMutation object of the builder.
func (_u *ProjectMembershipUpdateOne) Mutation() *ProjectMembershipMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ProjectMembershipUpdateOne) ClearUser() *ProjectMembershipUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectMembershipUpdateOne) ClearProject() *ProjectMembershipUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the ProjectMembershipUpdate builder.
func (_u *ProjectMembershipUpdateOne) Where(ps ...predicate.ProjectMembership) *ProjectMembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectMembershipUpdateOne) Select(field string, fields ...string) *ProjectMembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectMembership entity.
func (_u *ProjectMembershipUpdateOne) Save(ctx context.Context) (*ProjectMembership, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectMembershipUpdateOne) SaveX(ctx context.Context) *ProjectMembership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectMembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectMembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectMembershipUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := projectmembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ProjectMembership.role": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectMembership.user"`)
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectMembership.project"`)
	}
	return nil
}

func (_u *ProjectMembershipUpdateOne) sqlSave(ctx context.Context) (_node *ProjectMembership, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectmembership.Table, projectmembership.Columns, sqlgraph.NewFieldSpec(projectmembership.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectMembership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectmembership.FieldID)
		for _, f := range fields {
			if !projectmembership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectmembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(projectmembership.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmembership.UserTable,
			Columns: []string{projectmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmembership.UserTable,
			Columns: []string{projectmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmembership.ProjectTable,
			Columns: []string{projectmembership.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmembership.ProjectTable,
			Columns: []string{projectmembership.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectMembership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
