// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/plexlad/konservi/ent/entry"
	"github.com/plexlad/konservi/ent/family"
	"github.com/plexlad/konservi/ent/person"
	"github.com/plexlad/konservi/ent/project"
	"github.com/plexlad/konservi/ent/projectmembership"
	"github.com/plexlad/konservi/ent/user"
	"github.com/plexlad/konservi/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	entryFields := schema.Entry{}.Fields()
	_ = entryFields
	// entryDescContent is the schema descriptor for content field.
	entryDescContent := entryFields[3].Descriptor()
	// entry.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	entry.ContentValidator = entryDescContent.Validators[0].(func(string) error)
	// entryDescEntryDate is the schema descriptor for entry_date field.
	entryDescEntryDate := entryFields[4].Descriptor()
	// entry.DefaultEntryDate holds the default value on creation for the entry_date field.
	entry.DefaultEntryDate = entryDescEntryDate.Default.(func() time.Time)
	// entryDescCreatedAt is the schema descriptor for created_at field.
	entryDescCreatedAt := entryFields[5].Descriptor()
	// entry.DefaultCreatedAt holds the default value on creation for the created_at field.
	entry.DefaultCreatedAt = entryDescCreatedAt.Default.(func() time.Time)
	// entryDescEditedLastAt is the schema descriptor for edited_last_at field.
	entryDescEditedLastAt := entryFields[6].Descriptor()
	// entry.DefaultEditedLastAt holds the default value on creation for the edited_last_at field.
	entry.DefaultEditedLastAt = entryDescEditedLastAt.Default.(func() time.Time)
	// entryDescID is the schema descriptor for id field.
	entryDescID := entryFields[0].Descriptor()
	// entry.DefaultID holds the default value on creation for the id field.
	entry.DefaultID = entryDescID.Default.(func() uuid.UUID)
	familyFields := schema.Family{}.Fields()
	_ = familyFields
	// familyDescCreatedAt is the schema descriptor for created_at field.
	familyDescCreatedAt := familyFields[21].Descriptor()
	// family.DefaultCreatedAt holds the default value on creation for the created_at field.
	family.DefaultCreatedAt = familyDescCreatedAt.Default.(func() time.Time)
	// familyDescUpdatedAt is the schema descriptor for updated_at field.
	familyDescUpdatedAt := familyFields[22].Descriptor()
	// family.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	family.DefaultUpdatedAt = familyDescUpdatedAt.Default.(func() time.Time)
	// family.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	family.UpdateDefaultUpdatedAt = familyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// familyDescID is the schema descriptor for id field.
	familyDescID := familyFields[0].Descriptor()
	// family.DefaultID holds the default value on creation for the id field.
	family.DefaultID = familyDescID.Default.(func() uuid.UUID)
	personFields := schema.Person{}.Fields()
	_ = personFields
	// personDescPrimaryName is the schema descriptor for primary_name field.
	personDescPrimaryName := personFields[3].Descriptor()
	// person.PrimaryNameValidator is a validator for the "primary_name" field. It is called by the builders before save.
	person.PrimaryNameValidator = personDescPrimaryName.Validators[0].(func(string) error)
	// personDescCreatedAt is the schema descriptor for created_at field.
	personDescCreatedAt := personFields[41].Descriptor()
	// person.DefaultCreatedAt holds the default value on creation for the created_at field.
	person.DefaultCreatedAt = personDescCreatedAt.Default.(func() time.Time)
	// personDescUpdatedAt is the schema descriptor for updated_at field.
	personDescUpdatedAt := personFields[42].Descriptor()
	// person.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	person.DefaultUpdatedAt = personDescUpdatedAt.Default.(func() time.Time)
	// person.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	person.UpdateDefaultUpdatedAt = personDescUpdatedAt.UpdateDefault.(func() time.Time)
	// personDescID is the schema descriptor for id field.
	personDescID := personFields[0].Descriptor()
	// person.DefaultID holds the default value on creation for the id field.
	person.DefaultID = personDescID.Default.(func() uuid.UUID)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[1].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[4].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	projectmembershipFields := schema.ProjectMembership{}.Fields()
	_ = projectmembershipFields
	// projectmembershipDescJoinedAt is the schema descriptor for joined_at field.
	projectmembershipDescJoinedAt := projectmembershipFields[4].Descriptor()
	// projectmembership.DefaultJoinedAt holds the default value on creation for the joined_at field.
	projectmembership.DefaultJoinedAt = projectmembershipDescJoinedAt.Default.(func() time.Time)
	// projectmembershipDescID is the schema descriptor for id field.
	projectmembershipDescID := projectmembershipFields[0].Descriptor()
	// projectmembership.DefaultID holds the default value on creation for the id field.
	projectmembership.DefaultID = projectmembershipDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescEditedLastAt is the schema descriptor for edited_last_at field.
	userDescEditedLastAt := userFields[5].Descriptor()
	// user.DefaultEditedLastAt holds the default value on creation for the edited_last_at field.
	user.DefaultEditedLastAt = userDescEditedLastAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
