// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Entry is the predicate function for entry builders.
type Entry func(*sql.Selector)

// Family is the predicate function for family builders.
type Family func(*sql.Selector)

// Person is the predicate function for person builders.
type Person func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectMembership is the predicate function for projectmembership builders.
type ProjectMembership func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
