// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EntriesColumns holds the columns for the "entries" table.
	EntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "entry_date", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "edited_last_at", Type: field.TypeTime},
		{Name: "linked_person_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "family_entries", Type: field.TypeUUID, Nullable: true},
		{Name: "person_entries", Type: field.TypeUUID, Nullable: true},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "author_id", Type: field.TypeUUID},
	}
	// EntriesTable holds the schema information for the "entries" table.
	EntriesTable = &schema.Table{
		Name:       "entries",
		Columns:    EntriesColumns,
		PrimaryKey: []*schema.Column{EntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "entries_families_entries",
				Columns:    []*schema.Column{EntriesColumns[6]},
				RefColumns: []*schema.Column{FamiliesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "entries_persons_entries",
				Columns:    []*schema.Column{EntriesColumns[7]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "entries_projects_entries",
				Columns:    []*schema.Column{EntriesColumns[8]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "entries_users_entries",
				Columns:    []*schema.Column{EntriesColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "entry_project_id_entry_date",
				Unique:  false,
				Columns: []*schema.Column{EntriesColumns[8], EntriesColumns[2]},
			},
			{
				Name:    "entry_author_id",
				Unique:  false,
				Columns: []*schema.Column{EntriesColumns[9]},
			},
		},
	}
	// FamiliesColumns holds the columns for the "families" table.
	FamiliesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "uid", Type: field.TypeString, Nullable: true},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "spouse_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "marriage_date", Type: field.TypeTime, Nullable: true},
		{Name: "marriage_place", Type: field.TypeString, Nullable: true},
		{Name: "marriage_calendar", Type: field.TypeString, Nullable: true},
		{Name: "marriage_banns_date", Type: field.TypeTime, Nullable: true},
		{Name: "divorce_date", Type: field.TypeTime, Nullable: true},
		{Name: "annulment_date", Type: field.TypeTime, Nullable: true},
		{Name: "marriage_type", Type: field.TypeString, Nullable: true},
		{Name: "children_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "sources", Type: field.TypeJSON, Nullable: true},
		{Name: "shared_notes", Type: field.TypeJSON, Nullable: true},
		{Name: "privacy", Type: field.TypeEnum, Enums: []string{"public", "confidential", "private"}, Default: "public"},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "husband_id", Type: field.TypeUUID, Nullable: true},
		{Name: "wife_id", Type: field.TypeUUID, Nullable: true},
		{Name: "project_id", Type: field.TypeUUID},
	}
	// FamiliesTable holds the schema information for the "families" table.
	FamiliesTable = &schema.Table{
		Name:       "families",
		Columns:    FamiliesColumns,
		PrimaryKey: []*schema.Column{FamiliesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "families_persons_husband",
				Columns:    []*schema.Column{FamiliesColumns[20]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "families_persons_wife",
				Columns:    []*schema.Column{FamiliesColumns[21]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "families_projects_families",
				Columns:    []*schema.Column{FamiliesColumns[22]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "family_project_id_husband_id_wife_id",
				Unique:  false,
				Columns: []*schema.Column{FamiliesColumns[22], FamiliesColumns[20], FamiliesColumns[21]},
			},
			{
				Name:    "family_uid",
				Unique:  false,
				Columns: []*schema.Column{FamiliesColumns[1]},
			},
			{
				Name:    "family_external_id",
				Unique:  false,
				Columns: []*schema.Column{FamiliesColumns[2]},
			},
			{
				Name:    "family_marriage_date",
				Unique:  false,
				Columns: []*schema.Column{FamiliesColumns[4]},
			},
			{
				Name:    "family_privacy",
				Unique:  false,
				Columns: []*schema.Column{FamiliesColumns[15]},
			},
		},
	}
	// PersonsColumns holds the columns for the "persons" table.
	PersonsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "external_id", Type: field.TypeString, Nullable: true},
		{Name: "primary_name", Type: field.TypeString},
		{Name: "names", Type: field.TypeJSON, Nullable: true},
		{Name: "preferred_name", Type: field.TypeString, Nullable: true},
		{Name: "maiden_name", Type: field.TypeString, Nullable: true},
		{Name: "sex", Type: field.TypeEnum, Enums: []string{"M", "F", "U", "O", "X"}},
		{Name: "birth_date", Type: field.TypeTime, Nullable: true},
		{Name: "birth_date_approx", Type: field.TypeString, Nullable: true},
		{Name: "birth_place", Type: field.TypeString, Nullable: true},
		{Name: "birth_place_jurisdiction", Type: field.TypeJSON, Nullable: true},
		{Name: "death_date", Type: field.TypeTime, Nullable: true},
		{Name: "death_place", Type: field.TypeString, Nullable: true},
		{Name: "death_cause", Type: field.TypeString, Nullable: true},
		{Name: "death_details", Type: field.TypeJSON, Nullable: true},
		{Name: "burial_place", Type: field.TypeString, Nullable: true},
		{Name: "burial_date", Type: field.TypeTime, Nullable: true},
		{Name: "occupation", Type: field.TypeString, Nullable: true},
		{Name: "occupation_details", Type: field.TypeJSON, Nullable: true},
		{Name: "education", Type: field.TypeString, Nullable: true},
		{Name: "religion", Type: field.TypeString, Nullable: true},
		{Name: "nationality", Type: field.TypeString, Nullable: true},
		{Name: "ethnicity", Type: field.TypeString, Nullable: true},
		{Name: "aliases", Type: field.TypeJSON, Nullable: true},
		{Name: "nicknames", Type: field.TypeJSON, Nullable: true},
		{Name: "titles", Type: field.TypeJSON, Nullable: true},
		{Name: "height", Type: field.TypeJSON, Nullable: true},
		{Name: "weight", Type: field.TypeJSON, Nullable: true},
		{Name: "blood_type", Type: field.TypeJSON, Nullable: true},
		{Name: "medical_conditions", Type: field.TypeJSON, Nullable: true},
		{Name: "genetic_markers", Type: field.TypeJSON, Nullable: true},
		{Name: "dna_matches", Type: field.TypeJSON, Nullable: true},
		{Name: "photos", Type: field.TypeJSON, Nullable: true},
		{Name: "documents", Type: field.TypeJSON, Nullable: true},
		{Name: "events", Type: field.TypeJSON, Nullable: true},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "sources", Type: field.TypeJSON, Nullable: true},
		{Name: "shared_notes", Type: field.TypeJSON, Nullable: true},
		{Name: "media", Type: field.TypeJSON, Nullable: true},
		{Name: "privacy", Type: field.TypeEnum, Enums: []string{"public", "confidential", "private"}, Default: "public"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "family_spouses", Type: field.TypeUUID, Nullable: true},
		{Name: "father_id", Type: field.TypeUUID, Unique: true, Nullable: true},
		{Name: "mother_id", Type: field.TypeUUID, Unique: true, Nullable: true},
		{Name: "project_id", Type: field.TypeUUID},
	}
	// PersonsTable holds the schema information for the "persons" table.
	PersonsTable = &schema.Table{
		Name:       "persons",
		Columns:    PersonsColumns,
		PrimaryKey: []*schema.Column{PersonsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "persons_families_spouses",
				Columns:    []*schema.Column{PersonsColumns[44]},
				RefColumns: []*schema.Column{FamiliesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "persons_persons_father",
				Columns:    []*schema.Column{PersonsColumns[45]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "persons_persons_mother",
				Columns:    []*schema.Column{PersonsColumns[46]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "persons_projects_people",
				Columns:    []*schema.Column{PersonsColumns[47]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "person_project_id_primary_name",
				Unique:  false,
				Columns: []*schema.Column{PersonsColumns[47], PersonsColumns[2]},
			},
			{
				Name:    "person_id",
				Unique:  true,
				Columns: []*schema.Column{PersonsColumns[0]},
			},
			{
				Name:    "person_external_id",
				Unique:  false,
				Columns: []*schema.Column{PersonsColumns[1]},
			},
			{
				Name:    "person_birth_date",
				Unique:  false,
				Columns: []*schema.Column{PersonsColumns[7]},
			},
			{
				Name:    "person_death_date",
				Unique:  false,
				Columns: []*schema.Column{PersonsColumns[11]},
			},
			{
				Name:    "person_father_id_mother_id",
				Unique:  false,
				Columns: []*schema.Column{PersonsColumns[45], PersonsColumns[46]},
			},
			{
				Name:    "person_privacy",
				Unique:  false,
				Columns: []*schema.Column{PersonsColumns[39]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "owner_id", Type: field.TypeUUID},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "projects_users_projects",
				Columns:    []*schema.Column{ProjectsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "project_name",
				Unique:  false,
				Columns: []*schema.Column{ProjectsColumns[1]},
			},
		},
	}
	// ProjectMembershipsColumns holds the columns for the "project_memberships" table.
	ProjectMembershipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"owner", "admin", "editor", "viewer"}},
		{Name: "joined_at", Type: field.TypeTime},
		{Name: "project_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// ProjectMembershipsTable holds the schema information for the "project_memberships" table.
	ProjectMembershipsTable = &schema.Table{
		Name:       "project_memberships",
		Columns:    ProjectMembershipsColumns,
		PrimaryKey: []*schema.Column{ProjectMembershipsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_memberships_projects_memberships",
				Columns:    []*schema.Column{ProjectMembershipsColumns[3]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "project_memberships_users_memberships",
				Columns:    []*schema.Column{ProjectMembershipsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "projectmembership_user_id_project_id",
				Unique:  true,
				Columns: []*schema.Column{ProjectMembershipsColumns[4], ProjectMembershipsColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "edited_last_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username_email",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1], UsersColumns[2]},
			},
		},
	}
	// EntryLinkedPeopleColumns holds the columns for the "entry_linked_people" table.
	EntryLinkedPeopleColumns = []*schema.Column{
		{Name: "entry_id", Type: field.TypeUUID},
		{Name: "person_id", Type: field.TypeUUID},
	}
	// EntryLinkedPeopleTable holds the schema information for the "entry_linked_people" table.
	EntryLinkedPeopleTable = &schema.Table{
		Name:       "entry_linked_people",
		Columns:    EntryLinkedPeopleColumns,
		PrimaryKey: []*schema.Column{EntryLinkedPeopleColumns[0], EntryLinkedPeopleColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "entry_linked_people_entry_id",
				Columns:    []*schema.Column{EntryLinkedPeopleColumns[0]},
				RefColumns: []*schema.Column{EntriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "entry_linked_people_person_id",
				Columns:    []*schema.Column{EntryLinkedPeopleColumns[1]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// FamilyChildrenColumns holds the columns for the "family_children" table.
	FamilyChildrenColumns = []*schema.Column{
		{Name: "family_id", Type: field.TypeUUID},
		{Name: "person_id", Type: field.TypeUUID},
	}
	// FamilyChildrenTable holds the schema information for the "family_children" table.
	FamilyChildrenTable = &schema.Table{
		Name:       "family_children",
		Columns:    FamilyChildrenColumns,
		PrimaryKey: []*schema.Column{FamilyChildrenColumns[0], FamilyChildrenColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "family_children_family_id",
				Columns:    []*schema.Column{FamilyChildrenColumns[0]},
				RefColumns: []*schema.Column{FamiliesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "family_children_person_id",
				Columns:    []*schema.Column{FamilyChildrenColumns[1]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PersonChildrenColumns holds the columns for the "person_children" table.
	PersonChildrenColumns = []*schema.Column{
		{Name: "person_id", Type: field.TypeUUID},
		{Name: "child_id", Type: field.TypeUUID},
	}
	// PersonChildrenTable holds the schema information for the "person_children" table.
	PersonChildrenTable = &schema.Table{
		Name:       "person_children",
		Columns:    PersonChildrenColumns,
		PrimaryKey: []*schema.Column{PersonChildrenColumns[0], PersonChildrenColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "person_children_person_id",
				Columns:    []*schema.Column{PersonChildrenColumns[0]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "person_children_child_id",
				Columns:    []*schema.Column{PersonChildrenColumns[1]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PersonSpousesColumns holds the columns for the "person_spouses" table.
	PersonSpousesColumns = []*schema.Column{
		{Name: "person_id", Type: field.TypeUUID},
		{Name: "spouse_id", Type: field.TypeUUID},
	}
	// PersonSpousesTable holds the schema information for the "person_spouses" table.
	PersonSpousesTable = &schema.Table{
		Name:       "person_spouses",
		Columns:    PersonSpousesColumns,
		PrimaryKey: []*schema.Column{PersonSpousesColumns[0], PersonSpousesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "person_spouses_person_id",
				Columns:    []*schema.Column{PersonSpousesColumns[0]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "person_spouses_spouse_id",
				Columns:    []*schema.Column{PersonSpousesColumns[1]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PersonRelativesColumns holds the columns for the "person_relatives" table.
	PersonRelativesColumns = []*schema.Column{
		{Name: "person_id", Type: field.TypeUUID},
		{Name: "relative_id", Type: field.TypeUUID},
	}
	// PersonRelativesTable holds the schema information for the "person_relatives" table.
	PersonRelativesTable = &schema.Table{
		Name:       "person_relatives",
		Columns:    PersonRelativesColumns,
		PrimaryKey: []*schema.Column{PersonRelativesColumns[0], PersonRelativesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "person_relatives_person_id",
				Columns:    []*schema.Column{PersonRelativesColumns[0]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "person_relatives_relative_id",
				Columns:    []*schema.Column{PersonRelativesColumns[1]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PersonAssociationsColumns holds the columns for the "person_associations" table.
	PersonAssociationsColumns = []*schema.Column{
		{Name: "person_id", Type: field.TypeUUID},
		{Name: "association_id", Type: field.TypeUUID},
	}
	// PersonAssociationsTable holds the schema information for the "person_associations" table.
	PersonAssociationsTable = &schema.Table{
		Name:       "person_associations",
		Columns:    PersonAssociationsColumns,
		PrimaryKey: []*schema.Column{PersonAssociationsColumns[0], PersonAssociationsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "person_associations_person_id",
				Columns:    []*schema.Column{PersonAssociationsColumns[0]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "person_associations_association_id",
				Columns:    []*schema.Column{PersonAssociationsColumns[1]},
				RefColumns: []*schema.Column{PersonsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EntriesTable,
		FamiliesTable,
		PersonsTable,
		ProjectsTable,
		ProjectMembershipsTable,
		UsersTable,
		EntryLinkedPeopleTable,
		FamilyChildrenTable,
		PersonChildrenTable,
		PersonSpousesTable,
		PersonRelativesTable,
		PersonAssociationsTable,
	}
)

func init() {
	EntriesTable.ForeignKeys[0].RefTable = FamiliesTable
	EntriesTable.ForeignKeys[1].RefTable = PersonsTable
	EntriesTable.ForeignKeys[2].RefTable = ProjectsTable
	EntriesTable.ForeignKeys[3].RefTable = UsersTable
	FamiliesTable.ForeignKeys[0].RefTable = PersonsTable
	FamiliesTable.ForeignKeys[1].RefTable = PersonsTable
	FamiliesTable.ForeignKeys[2].RefTable = ProjectsTable
	PersonsTable.ForeignKeys[0].RefTable = FamiliesTable
	PersonsTable.ForeignKeys[1].RefTable = PersonsTable
	PersonsTable.ForeignKeys[2].RefTable = PersonsTable
	PersonsTable.ForeignKeys[3].RefTable = ProjectsTable
	ProjectsTable.ForeignKeys[0].RefTable = UsersTable
	ProjectMembershipsTable.ForeignKeys[0].RefTable = ProjectsTable
	ProjectMembershipsTable.ForeignKeys[1].RefTable = UsersTable
	EntryLinkedPeopleTable.ForeignKeys[0].RefTable = EntriesTable
	EntryLinkedPeopleTable.ForeignKeys[1].RefTable = PersonsTable
	FamilyChildrenTable.ForeignKeys[0].RefTable = FamiliesTable
	FamilyChildrenTable.ForeignKeys[1].RefTable = PersonsTable
	PersonChildrenTable.ForeignKeys[0].RefTable = PersonsTable
	PersonChildrenTable.ForeignKeys[1].RefTable = PersonsTable
	PersonSpousesTable.ForeignKeys[0].RefTable = PersonsTable
	PersonSpousesTable.ForeignKeys[1].RefTable = PersonsTable
	PersonRelativesTable.ForeignKeys[0].RefTable = PersonsTable
	PersonRelativesTable.ForeignKeys[1].RefTable = PersonsTable
	PersonAssociationsTable.ForeignKeys[0].RefTable = PersonsTable
	PersonAssociationsTable.ForeignKeys[1].RefTable = PersonsTable
}
