// Code generated by ent, DO NOT EDIT.

package entry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the entry type in the database.
	Label = "entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldAuthorID holds the string denoting the author_id field in the database.
	FieldAuthorID = "author_id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldEntryDate holds the string denoting the entry_date field in the database.
	FieldEntryDate = "entry_date"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldEditedLastAt holds the string denoting the edited_last_at field in the database.
	FieldEditedLastAt = "edited_last_at"
	// FieldLinkedPersonIds holds the string denoting the linked_person_ids field in the database.
	FieldLinkedPersonIds = "linked_person_ids"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeAuthor holds the string denoting the author edge name in mutations.
	EdgeAuthor = "author"
	// EdgeLinkedPeople holds the string denoting the linked_people edge name in mutations.
	EdgeLinkedPeople = "linked_people"
	// Table holds the table name of the entry in the database.
	Table = "entries"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "entries"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// AuthorTable is the table that holds the author relation/edge.
	AuthorTable = "entries"
	// AuthorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AuthorInverseTable = "users"
	// AuthorColumn is the table column denoting the author relation/edge.
	AuthorColumn = "author_id"
	// LinkedPeopleTable is the table that holds the linked_people relation/edge. The primary key declared below.
	LinkedPeopleTable = "entry_linked_people"
	// LinkedPeopleInverseTable is the table name for the Person entity.
	// It exists in this package in order to avoid circular dependency with the "person" package.
	LinkedPeopleInverseTable = "persons"
)

// Columns holds all SQL columns for entry fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldAuthorID,
	FieldContent,
	FieldEntryDate,
	FieldCreatedAt,
	FieldEditedLastAt,
	FieldLinkedPersonIds,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "entries"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"family_entries",
	"person_entries",
}

var (
	// LinkedPeoplePrimaryKey and LinkedPeopleColumn2 are the table columns denoting the
	// primary key for the linked_people relation (M2M).
	LinkedPeoplePrimaryKey = []string{"entry_id", "person_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// DefaultEntryDate holds the default value on creation for the "entry_date" field.
	DefaultEntryDate func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultEditedLastAt holds the default value on creation for the "edited_last_at" field.
	DefaultEditedLastAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Entry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByAuthorID orders the results by the author_id field.
func ByAuthorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorID, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByEntryDate orders the results by the entry_date field.
func ByEntryDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryDate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByEditedLastAt orders the results by the edited_last_at field.
func ByEditedLastAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEditedLastAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByAuthorField orders the results by author field.
func ByAuthorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthorStep(), sql.OrderByField(field, opts...))
	}
}

// ByLinkedPeopleCount orders the results by linked_people count.
func ByLinkedPeopleCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLinkedPeopleStep(), opts...)
	}
}

// ByLinkedPeople orders the results by linked_people terms.
func ByLinkedPeople(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLinkedPeopleStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newAuthorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
	)
}
func newLinkedPeopleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LinkedPeopleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, LinkedPeopleTable, LinkedPeoplePrimaryKey...),
	)
}
