// Code generated by ent, DO NOT EDIT.

package family

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/plexlad/konservi/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldProjectID, v))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldUID, v))
}

// ExternalID applies equality check predicate on the "external_id" field. It's identical to ExternalIDEQ.
func ExternalID(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldExternalID, v))
}

// HusbandID applies equality check predicate on the "husband_id" field. It's identical to HusbandIDEQ.
func HusbandID(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldHusbandID, v))
}

// WifeID applies equality check predicate on the "wife_id" field. It's identical to WifeIDEQ.
func WifeID(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldWifeID, v))
}

// MarriageDate applies equality check predicate on the "marriage_date" field. It's identical to MarriageDateEQ.
func MarriageDate(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldMarriageDate, v))
}

// MarriagePlace applies equality check predicate on the "marriage_place" field. It's identical to MarriagePlaceEQ.
func MarriagePlace(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldMarriagePlace, v))
}

// MarriageCalendar applies equality check predicate on the "marriage_calendar" field. It's identical to MarriageCalendarEQ.
func MarriageCalendar(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldMarriageCalendar, v))
}

// MarriageBannsDate applies equality check predicate on the "marriage_banns_date" field. It's identical to MarriageBannsDateEQ.
func MarriageBannsDate(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldMarriageBannsDate, v))
}

// DivorceDate applies equality check predicate on the "divorce_date" field. It's identical to DivorceDateEQ.
func DivorceDate(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldDivorceDate, v))
}

// AnnulmentDate applies equality check predicate on the "annulment_date" field. It's identical to AnnulmentDateEQ.
func AnnulmentDate(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldAnnulmentDate, v))
}

// MarriageType applies equality check predicate on the "marriage_type" field. It's identical to MarriageTypeEQ.
func MarriageType(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldMarriageType, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldNotes, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldProjectID, vs...))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v string) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v string) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v string) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v string) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldUID, v))
}

// UIDContains applies the Contains predicate on the "uid" field.
func UIDContains(v string) predicate.Family {
	return predicate.Family(sql.FieldContains(FieldUID, v))
}

// UIDHasPrefix applies the HasPrefix predicate on the "uid" field.
func UIDHasPrefix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasPrefix(FieldUID, v))
}

// UIDHasSuffix applies the HasSuffix predicate on the "uid" field.
func UIDHasSuffix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasSuffix(FieldUID, v))
}

// UIDIsNil applies the IsNil predicate on the "uid" field.
func UIDIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldUID))
}

// UIDNotNil applies the NotNil predicate on the "uid" field.
func UIDNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldUID))
}

// UIDEqualFold applies the EqualFold predicate on the "uid" field.
func UIDEqualFold(v string) predicate.Family {
	return predicate.Family(sql.FieldEqualFold(FieldUID, v))
}

// UIDContainsFold applies the ContainsFold predicate on the "uid" field.
func UIDContainsFold(v string) predicate.Family {
	return predicate.Family(sql.FieldContainsFold(FieldUID, v))
}

// ExternalIDEQ applies the EQ predicate on the "external_id" field.
func ExternalIDEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldExternalID, v))
}

// ExternalIDNEQ applies the NEQ predicate on the "external_id" field.
func ExternalIDNEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldExternalID, v))
}

// ExternalIDIn applies the In predicate on the "external_id" field.
func ExternalIDIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldExternalID, vs...))
}

// ExternalIDNotIn applies the NotIn predicate on the "external_id" field.
func ExternalIDNotIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldExternalID, vs...))
}

// ExternalIDGT applies the GT predicate on the "external_id" field.
func ExternalIDGT(v string) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldExternalID, v))
}

// ExternalIDGTE applies the GTE predicate on the "external_id" field.
func ExternalIDGTE(v string) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldExternalID, v))
}

// ExternalIDLT applies the LT predicate on the "external_id" field.
func ExternalIDLT(v string) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldExternalID, v))
}

// ExternalIDLTE applies the LTE predicate on the "external_id" field.
func ExternalIDLTE(v string) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldExternalID, v))
}

// ExternalIDContains applies the Contains predicate on the "external_id" field.
func ExternalIDContains(v string) predicate.Family {
	return predicate.Family(sql.FieldContains(FieldExternalID, v))
}

// ExternalIDHasPrefix applies the HasPrefix predicate on the "external_id" field.
func ExternalIDHasPrefix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasPrefix(FieldExternalID, v))
}

// ExternalIDHasSuffix applies the HasSuffix predicate on the "external_id" field.
func ExternalIDHasSuffix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasSuffix(FieldExternalID, v))
}

// ExternalIDIsNil applies the IsNil predicate on the "external_id" field.
func ExternalIDIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldExternalID))
}

// ExternalIDNotNil applies the NotNil predicate on the "external_id" field.
func ExternalIDNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldExternalID))
}

// ExternalIDEqualFold applies the EqualFold predicate on the "external_id" field.
func ExternalIDEqualFold(v string) predicate.Family {
	return predicate.Family(sql.FieldEqualFold(FieldExternalID, v))
}

// ExternalIDContainsFold applies the ContainsFold predicate on the "external_id" field.
func ExternalIDContainsFold(v string) predicate.Family {
	return predicate.Family(sql.FieldContainsFold(FieldExternalID, v))
}

// HusbandIDEQ applies the EQ predicate on the "husband_id" field.
func HusbandIDEQ(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldHusbandID, v))
}

// HusbandIDNEQ applies the NEQ predicate on the "husband_id" field.
func HusbandIDNEQ(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldHusbandID, v))
}

// HusbandIDIn applies the In predicate on the "husband_id" field.
func HusbandIDIn(vs ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldHusbandID, vs...))
}

// HusbandIDNotIn applies the NotIn predicate on the "husband_id" field.
func HusbandIDNotIn(vs ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldHusbandID, vs...))
}

// HusbandIDIsNil applies the IsNil predicate on the "husband_id" field.
func HusbandIDIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldHusbandID))
}

// HusbandIDNotNil applies the NotNil predicate on the "husband_id" field.
func HusbandIDNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldHusbandID))
}

// WifeIDEQ applies the EQ predicate on the "wife_id" field.
func WifeIDEQ(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldWifeID, v))
}

// WifeIDNEQ applies the NEQ predicate on the "wife_id" field.
func WifeIDNEQ(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldWifeID, v))
}

// WifeIDIn applies the In predicate on the "wife_id" field.
func WifeIDIn(vs ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldWifeID, vs...))
}

// WifeIDNotIn applies the NotIn predicate on the "wife_id" field.
func WifeIDNotIn(vs ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldWifeID, vs...))
}

// WifeIDIsNil applies the IsNil predicate on the "wife_id" field.
func WifeIDIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldWifeID))
}

// WifeIDNotNil applies the NotNil predicate on the "wife_id" field.
func WifeIDNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldWifeID))
}

// SpouseIdsIsNil applies the IsNil predicate on the "spouse_ids" field.
func SpouseIdsIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldSpouseIds))
}

// SpouseIdsNotNil applies the NotNil predicate on the "spouse_ids" field.
func SpouseIdsNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldSpouseIds))
}

// MarriageDateEQ applies the EQ predicate on the "marriage_date" field.
func MarriageDateEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldMarriageDate, v))
}

// MarriageDateNEQ applies the NEQ predicate on the "marriage_date" field.
func MarriageDateNEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldMarriageDate, v))
}

// MarriageDateIn applies the In predicate on the "marriage_date" field.
func MarriageDateIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldMarriageDate, vs...))
}

// MarriageDateNotIn applies the NotIn predicate on the "marriage_date" field.
func MarriageDateNotIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldMarriageDate, vs...))
}

// MarriageDateGT applies the GT predicate on the "marriage_date" field.
func MarriageDateGT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldMarriageDate, v))
}

// MarriageDateGTE applies the GTE predicate on the "marriage_date" field.
func MarriageDateGTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldMarriageDate, v))
}

// MarriageDateLT applies the LT predicate on the "marriage_date" field.
func MarriageDateLT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldMarriageDate, v))
}

// MarriageDateLTE applies the LTE predicate on the "marriage_date" field.
func MarriageDateLTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldMarriageDate, v))
}

// MarriageDateIsNil applies the IsNil predicate on the "marriage_date" field.
func MarriageDateIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldMarriageDate))
}

// MarriageDateNotNil applies the NotNil predicate on the "marriage_date" field.
func MarriageDateNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldMarriageDate))
}

// MarriagePlaceEQ applies the EQ predicate on the "marriage_place" field.
func MarriagePlaceEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldMarriagePlace, v))
}

// MarriagePlaceNEQ applies the NEQ predicate on the "marriage_place" field.
func MarriagePlaceNEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldMarriagePlace, v))
}

// MarriagePlaceIn applies the In predicate on the "marriage_place" field.
func MarriagePlaceIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldMarriagePlace, vs...))
}

// MarriagePlaceNotIn applies the NotIn predicate on the "marriage_place" field.
func MarriagePlaceNotIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldMarriagePlace, vs...))
}

// MarriagePlaceGT applies the GT predicate on the "marriage_place" field.
func MarriagePlaceGT(v string) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldMarriagePlace, v))
}

// MarriagePlaceGTE applies the GTE predicate on the "marriage_place" field.
func MarriagePlaceGTE(v string) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldMarriagePlace, v))
}

// MarriagePlaceLT applies the LT predicate on the "marriage_place" field.
func MarriagePlaceLT(v string) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldMarriagePlace, v))
}

// MarriagePlaceLTE applies the LTE predicate on the "marriage_place" field.
func MarriagePlaceLTE(v string) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldMarriagePlace, v))
}

// MarriagePlaceContains applies the Contains predicate on the "marriage_place" field.
func MarriagePlaceContains(v string) predicate.Family {
	return predicate.Family(sql.FieldContains(FieldMarriagePlace, v))
}

// MarriagePlaceHasPrefix applies the HasPrefix predicate on the "marriage_place" field.
func MarriagePlaceHasPrefix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasPrefix(FieldMarriagePlace, v))
}

// MarriagePlaceHasSuffix applies the HasSuffix predicate on the "marriage_place" field.
func MarriagePlaceHasSuffix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasSuffix(FieldMarriagePlace, v))
}

// MarriagePlaceIsNil applies the IsNil predicate on the "marriage_place" field.
func MarriagePlaceIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldMarriagePlace))
}

// MarriagePlaceNotNil applies the NotNil predicate on the "marriage_place" field.
func MarriagePlaceNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldMarriagePlace))
}

// MarriagePlaceEqualFold applies the EqualFold predicate on the "marriage_place" field.
func MarriagePlaceEqualFold(v string) predicate.Family {
	return predicate.Family(sql.FieldEqualFold(FieldMarriagePlace, v))
}

// MarriagePlaceContainsFold applies the ContainsFold predicate on the "marriage_place" field.
func MarriagePlaceContainsFold(v string) predicate.Family {
	return predicate.Family(sql.FieldContainsFold(FieldMarriagePlace, v))
}

// MarriageCalendarEQ applies the EQ predicate on the "marriage_calendar" field.
func MarriageCalendarEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldMarriageCalendar, v))
}

// MarriageCalendarNEQ applies the NEQ predicate on the "marriage_calendar" field.
func MarriageCalendarNEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldMarriageCalendar, v))
}

// MarriageCalendarIn applies the In predicate on the "marriage_calendar" field.
func MarriageCalendarIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldMarriageCalendar, vs...))
}

// MarriageCalendarNotIn applies the NotIn predicate on the "marriage_calendar" field.
func MarriageCalendarNotIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldMarriageCalendar, vs...))
}

// MarriageCalendarGT applies the GT predicate on the "marriage_calendar" field.
func MarriageCalendarGT(v string) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldMarriageCalendar, v))
}

// MarriageCalendarGTE applies the GTE predicate on the "marriage_calendar" field.
func MarriageCalendarGTE(v string) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldMarriageCalendar, v))
}

// MarriageCalendarLT applies the LT predicate on the "marriage_calendar" field.
func MarriageCalendarLT(v string) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldMarriageCalendar, v))
}

// MarriageCalendarLTE applies the LTE predicate on the "marriage_calendar" field.
func MarriageCalendarLTE(v string) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldMarriageCalendar, v))
}

// MarriageCalendarContains applies the Contains predicate on the "marriage_calendar" field.
func MarriageCalendarContains(v string) predicate.Family {
	return predicate.Family(sql.FieldContains(FieldMarriageCalendar, v))
}

// MarriageCalendarHasPrefix applies the HasPrefix predicate on the "marriage_calendar" field.
func MarriageCalendarHasPrefix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasPrefix(FieldMarriageCalendar, v))
}

// MarriageCalendarHasSuffix applies the HasSuffix predicate on the "marriage_calendar" field.
func MarriageCalendarHasSuffix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasSuffix(FieldMarriageCalendar, v))
}

// MarriageCalendarIsNil applies the IsNil predicate on the "marriage_calendar" field.
func MarriageCalendarIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldMarriageCalendar))
}

// MarriageCalendarNotNil applies the NotNil predicate on the "marriage_calendar" field.
func MarriageCalendarNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldMarriageCalendar))
}

// MarriageCalendarEqualFold applies the EqualFold predicate on the "marriage_calendar" field.
func MarriageCalendarEqualFold(v string) predicate.Family {
	return predicate.Family(sql.FieldEqualFold(FieldMarriageCalendar, v))
}

// MarriageCalendarContainsFold applies the ContainsFold predicate on the "marriage_calendar" field.
func MarriageCalendarContainsFold(v string) predicate.Family {
	return predicate.Family(sql.FieldContainsFold(FieldMarriageCalendar, v))
}

// MarriageBannsDateEQ applies the EQ predicate on the "marriage_banns_date" field.
func MarriageBannsDateEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldMarriageBannsDate, v))
}

// MarriageBannsDateNEQ applies the NEQ predicate on the "marriage_banns_date" field.
func MarriageBannsDateNEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldMarriageBannsDate, v))
}

// MarriageBannsDateIn applies the In predicate on the "marriage_banns_date" field.
func MarriageBannsDateIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldMarriageBannsDate, vs...))
}

// MarriageBannsDateNotIn applies the NotIn predicate on the "marriage_banns_date" field.
func MarriageBannsDateNotIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldMarriageBannsDate, vs...))
}

// MarriageBannsDateGT applies the GT predicate on the "marriage_banns_date" field.
func MarriageBannsDateGT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldMarriageBannsDate, v))
}

// MarriageBannsDateGTE applies the GTE predicate on the "marriage_banns_date" field.
func MarriageBannsDateGTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldMarriageBannsDate, v))
}

// MarriageBannsDateLT applies the LT predicate on the "marriage_banns_date" field.
func MarriageBannsDateLT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldMarriageBannsDate, v))
}

// MarriageBannsDateLTE applies the LTE predicate on the "marriage_banns_date" field.
func MarriageBannsDateLTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldMarriageBannsDate, v))
}

// MarriageBannsDateIsNil applies the IsNil predicate on the "marriage_banns_date" field.
func MarriageBannsDateIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldMarriageBannsDate))
}

// MarriageBannsDateNotNil applies the NotNil predicate on the "marriage_banns_date" field.
func MarriageBannsDateNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldMarriageBannsDate))
}

// DivorceDateEQ applies the EQ predicate on the "divorce_date" field.
func DivorceDateEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldDivorceDate, v))
}

// DivorceDateNEQ applies the NEQ predicate on the "divorce_date" field.
func DivorceDateNEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldDivorceDate, v))
}

// DivorceDateIn applies the In predicate on the "divorce_date" field.
func DivorceDateIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldDivorceDate, vs...))
}

// DivorceDateNotIn applies the NotIn predicate on the "divorce_date" field.
func DivorceDateNotIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldDivorceDate, vs...))
}

// DivorceDateGT applies the GT predicate on the "divorce_date" field.
func DivorceDateGT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldDivorceDate, v))
}

// DivorceDateGTE applies the GTE predicate on the "divorce_date" field.
func DivorceDateGTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldDivorceDate, v))
}

// DivorceDateLT applies the LT predicate on the "divorce_date" field.
func DivorceDateLT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldDivorceDate, v))
}

// DivorceDateLTE applies the LTE predicate on the "divorce_date" field.
func DivorceDateLTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldDivorceDate, v))
}

// DivorceDateIsNil applies the IsNil predicate on the "divorce_date" field.
func DivorceDateIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldDivorceDate))
}

// DivorceDateNotNil applies the NotNil predicate on the "divorce_date" field.
func DivorceDateNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldDivorceDate))
}

// AnnulmentDateEQ applies the EQ predicate on the "annulment_date" field.
func AnnulmentDateEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldAnnulmentDate, v))
}

// AnnulmentDateNEQ applies the NEQ predicate on the "annulment_date" field.
func AnnulmentDateNEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldAnnulmentDate, v))
}

// AnnulmentDateIn applies the In predicate on the "annulment_date" field.
func AnnulmentDateIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldAnnulmentDate, vs...))
}

// AnnulmentDateNotIn applies the NotIn predicate on the "annulment_date" field.
func AnnulmentDateNotIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldAnnulmentDate, vs...))
}

// AnnulmentDateGT applies the GT predicate on the "annulment_date" field.
func AnnulmentDateGT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldAnnulmentDate, v))
}

// AnnulmentDateGTE applies the GTE predicate on the "annulment_date" field.
func AnnulmentDateGTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldAnnulmentDate, v))
}

// AnnulmentDateLT applies the LT predicate on the "annulment_date" field.
func AnnulmentDateLT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldAnnulmentDate, v))
}

// AnnulmentDateLTE applies the LTE predicate on the "annulment_date" field.
func AnnulmentDateLTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldAnnulmentDate, v))
}

// AnnulmentDateIsNil applies the IsNil predicate on the "annulment_date" field.
func AnnulmentDateIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldAnnulmentDate))
}

// AnnulmentDateNotNil applies the NotNil predicate on the "annulment_date" field.
func AnnulmentDateNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldAnnulmentDate))
}

// MarriageTypeEQ applies the EQ predicate on the "marriage_type" field.
func MarriageTypeEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldMarriageType, v))
}

// MarriageTypeNEQ applies the NEQ predicate on the "marriage_type" field.
func MarriageTypeNEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldMarriageType, v))
}

// MarriageTypeIn applies the In predicate on the "marriage_type" field.
func MarriageTypeIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldMarriageType, vs...))
}

// MarriageTypeNotIn applies the NotIn predicate on the "marriage_type" field.
func MarriageTypeNotIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldMarriageType, vs...))
}

// MarriageTypeGT applies the GT predicate on the "marriage_type" field.
func MarriageTypeGT(v string) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldMarriageType, v))
}

// MarriageTypeGTE applies the GTE predicate on the "marriage_type" field.
func MarriageTypeGTE(v string) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldMarriageType, v))
}

// MarriageTypeLT applies the LT predicate on the "marriage_type" field.
func MarriageTypeLT(v string) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldMarriageType, v))
}

// MarriageTypeLTE applies the LTE predicate on the "marriage_type" field.
func MarriageTypeLTE(v string) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldMarriageType, v))
}

// MarriageTypeContains applies the Contains predicate on the "marriage_type" field.
func MarriageTypeContains(v string) predicate.Family {
	return predicate.Family(sql.FieldContains(FieldMarriageType, v))
}

// MarriageTypeHasPrefix applies the HasPrefix predicate on the "marriage_type" field.
func MarriageTypeHasPrefix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasPrefix(FieldMarriageType, v))
}

// MarriageTypeHasSuffix applies the HasSuffix predicate on the "marriage_type" field.
func MarriageTypeHasSuffix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasSuffix(FieldMarriageType, v))
}

// MarriageTypeIsNil applies the IsNil predicate on the "marriage_type" field.
func MarriageTypeIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldMarriageType))
}

// MarriageTypeNotNil applies the NotNil predicate on the "marriage_type" field.
func MarriageTypeNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldMarriageType))
}

// MarriageTypeEqualFold applies the EqualFold predicate on the "marriage_type" field.
func MarriageTypeEqualFold(v string) predicate.Family {
	return predicate.Family(sql.FieldEqualFold(FieldMarriageType, v))
}

// MarriageTypeContainsFold applies the ContainsFold predicate on the "marriage_type" field.
func MarriageTypeContainsFold(v string) predicate.Family {
	return predicate.Family(sql.FieldContainsFold(FieldMarriageType, v))
}

// ChildrenIdsIsNil applies the IsNil predicate on the "children_ids" field.
func ChildrenIdsIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldChildrenIds))
}

// ChildrenIdsNotNil applies the NotNil predicate on the "children_ids" field.
func ChildrenIdsNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldChildrenIds))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Family {
	return predicate.Family(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Family {
	return predicate.Family(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Family {
	return predicate.Family(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Family {
	return predicate.Family(sql.FieldContainsFold(FieldNotes, v))
}

// SourcesIsNil applies the IsNil predicate on the "sources" field.
func SourcesIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldSources))
}

// SourcesNotNil applies the NotNil predicate on the "sources" field.
func SourcesNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldSources))
}

// SharedNotesIsNil applies the IsNil predicate on the "shared_notes" field.
func SharedNotesIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldSharedNotes))
}

// SharedNotesNotNil applies the NotNil predicate on the "shared_notes" field.
func SharedNotesNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldSharedNotes))
}

// PrivacyEQ applies the EQ predicate on the "privacy" field.
func PrivacyEQ(v Privacy) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldPrivacy, v))
}

// PrivacyNEQ applies the NEQ predicate on the "privacy" field.
func PrivacyNEQ(v Privacy) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldPrivacy, v))
}

// PrivacyIn applies the In predicate on the "privacy" field.
func PrivacyIn(vs ...Privacy) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldPrivacy, vs...))
}

// PrivacyNotIn applies the NotIn predicate on the "privacy" field.
func PrivacyNotIn(vs ...Privacy) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldPrivacy, vs...))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uuid.UUID) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Family {
	return predicate.Family(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Family {
	return predicate.Family(sql.FieldNotNull(FieldUpdatedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Family {
	return predicate.Family(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Family {
	return predicate.Family(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHusband applies the HasEdge predicate on the "husband" edge.
func HasHusband() predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, HusbandTable, HusbandColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHusbandWith applies the HasEdge predicate on the "husband" edge with a given conditions (other predicates).
func HasHusbandWith(preds ...predicate.Person) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := newHusbandStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWife applies the HasEdge predicate on the "wife" edge.
func HasWife() predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, WifeTable, WifeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWifeWith applies the HasEdge predicate on the "wife" edge with a given conditions (other predicates).
func HasWifeWith(preds ...predicate.Person) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := newWifeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSpouses applies the HasEdge predicate on the "spouses" edge.
func HasSpouses() predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SpousesTable, SpousesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSpousesWith applies the HasEdge predicate on the "spouses" edge with a given conditions (other predicates).
func HasSpousesWith(preds ...predicate.Person) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := newSpousesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ChildrenTable, ChildrenPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.Person) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := newChildrenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEntries applies the HasEdge predicate on the "entries" edge.
func HasEntries() predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EntriesTable, EntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntriesWith applies the HasEdge predicate on the "entries" edge with a given conditions (other predicates).
func HasEntriesWith(preds ...predicate.Entry) predicate.Family {
	return predicate.Family(func(s *sql.Selector) {
		step := newEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Family) predicate.Family {
	return predicate.Family(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Family) predicate.Family {
	return predicate.Family(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Family) predicate.Family {
	return predicate.Family(sql.NotPredicates(p))
}
